EXTRA_GOFAST_OUT = Mgithub.com/pensando/sw/api/protos/smartnic.proto=github.com/pensando/sw/api/generated/cluster,
EXTRA_INCLUDES = -I../../../../api/protos
SERVICE_PROTOS = $(wildcard *.proto)
include ../../../../venice/Makefile.proto