#include "../include/headers.p4"
#include "../include/artemis_defines.h"
#include "../include/artemis_headers.p4"
#include "../include/artemis_table_sizes.h"
#include "../include/lpm_defines.h"

#include "rxlpm1.p4"
#include "rxlpm2.p4"
#include "recirc.p4"
#include "vnic_info_rxdma.p4"
#include "packet_queue.p4"
#include "nat_rxdma.p4"
#include "session_aging.p4"

#include "common_rxdma_dummy_actions.p4"
#include "common_rxdma.p4"
#include "metadata.p4"
