package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpcietlp_hdrs",
    hdrs = [
        "pcietlp.h",
    ],
    include_prefix = "platform/src/lib/pcietlp/include",
)

