client.delphi.go:
	protoc --delphigo_out=Mdelphi.proto=github.com/pensando/sw/nic/delphi/proto/delphi:. \
		${GOPATH}/src/github.com/pensando/sw/nic/delphi/sdk/proto/client.proto -I${GOPATH}/src -I ${GOPATH}/src/github.com/pensando/sw -I . -I${GOPATH}/src/github.com/pensando/sw/nic/delphi/proto/delphi
