package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libsimdev_hdrs",
    hdrs = [
        "simdevices.h",
    ],
    include_prefix = "platform/src/sim/libsimdev/include",
)

