
TOPDIR = ../../../..
# SHAREDLIBRARY = libpddirectmap.so
BUILDOBJS = xx

LCXXFLAGS = \
			-I.. \
			-I../../../../include \
			-I../../../../hal/pd \
			-I../../../../gen/iris/include \
			-I../../../../third-party/spdlog/include

SOURCES = \
	directmap.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
