#!/bin/sh

# /usr/pensando/bin of host (or VM) is mapped to /home/usr/pensando/bin inside the base container.
# The binaries (which need to be run on the host) are packaged in the base container.
# Steps below copy the binaries to be run on the host.
#   Also any config files are copied here too.
#  Please note that binaries must be Static binaries (hence we dont have to worry about presence of dynamic libraries on host)
mv -f /target/usr/bin/systemd-docker /host/usr/pensando/bin/systemd-docker
mv -f /target/usr/bin/kubelet /host/usr/pensando/bin/kubelet
mv -f /target/usr/lib/systemd/system/* /host/usr/lib/systemd/system/
mv -f /target/etc/pensando/influxdb.conf /host/etc/pensando/influxdb.conf
