

LIBDIRS = \
	  tcp/rx \
	  tcp/tx \
	  tls \
	  tls/pre_crypto_enc \
	  tls/pre_crypto_dec \
	  tls/post_crypto_enc \
	  tls/post_crypto_dec \
          $(NULL)
PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..

include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc

