package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libmisc_hdrs",
    hdrs = [
        "bdf.h",
        "maclib.h",
        "misc.h",
    ],
    include_prefix = "platform/src/lib/misc/include",
)

