export TOPDIR   := ${realpath ${CURDIR}}
export SDKDIR   := ${TOPDIR}
export BLDTOP   := ${TOPDIR}
export MAKEDEFS := ${TOPDIR}/makedefs

include ${MAKEDEFS}/config.mk
include ${MAKEDEFS}/generator.mk

.DEFAULT_GOAL := all

.PHONY: all clean
all: ${ALL_TARGETS} 

clean:
	@rm -rf ${BLD_ARCH_DIR}
