# Gtest
new_git_repository(
    name = "gtest",
    build_file = "BUILD.gtest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.8.0",
)

new_local_repository(
    name = 'linaro_linux_gcc_repo',
    build_file = '../../compilers/linaro_linux_gcc.BUILD',
    path = '/tool/toolchain/aarch64',
)
