package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpcieport_hdrs",
    hdrs = [
        "pcieport.h",
        "pcieport_events.h",
        "portcfg.h",
    ],
    include_prefix = "platform/src/lib/pcieport/include",
)

