package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license
cc_library(
    name = "linkmgr",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//:sdk_headers",
        "//lib/catalog:catalog",
    ],
)
