TOPDIR = ../../..
LIBRARY = libhalproto.so

LCXXFLAGS = \
			-I/usr/local/include \
			-I$(TOPDIR)/hal/third-party/google/include \
			-I$(TOPDIR)/hal/third-party/grpc/include \
			-pthread \
			-O3 \
			$(NULL)

SOURCES = $(wildcard *.cc)

include $(TOPDIR)/make/Makefile_platform.inc
include $(TOPDIR)/make/build.mk
