
TOPDIR = ../..
SHAREDLIBRARY = libproto.so

LCXXFLAGS = \
			-I/usr/local/include \
			-pthread \
			-g \
			$(NULL)

SOURCES = $(wildcard *.cc)

include $(TOPDIR)/make/Makefile.inc

# Adding more clean files
# LCLEANFILES = $(OBJ_DIR)/*.pb.o $(GEN_DIR)/*.pb.* $(GEN_DIR)/*.pb-c.*

