#################################################
############### RUN-GTESTS ######################
#################################################
ifneq ($(ARCH),aarch64)
    ARCH = x86_64
endif
export NON_PERSISTENT_LOGDIR=$(TOPDIR)
GEN_TEST_RESULTS_DIR = $(TOPDIR)/gen/test_results
SNORT_EXPORT_DIR = $(TOPDIR)/hal/third-party/snort3/export
SNORT_CMD_OPTS = SNORT_LUA_PATH=$(SNORT_EXPORT_DIR)/lua/ LUA_PATH="$(SNORT_EXPORT_DIR)/lua/?.lua;;" SNORT_DAQ_PATH=$(SNORT_EXPORT_DIR)/$(ARCH)/lib/
CONFIG_PATH = $(TOPDIR)/conf
LD_PATH = $(LD_LIBRARY_PATH):$(TOPDIR)/../bazel-bin/nic/sdk/model_sim/:$(SNORT_EXPORT_DIR)/$(ARCH)/lib/:$(TOPDIR)/sdk/obj/lib:$(TOPDIR)/sdk/obj/lib/external:$(TOPDIR)/hal/obj:$(TOPDIR)/hal/third-party/sknobs/x86_64/lib/
CMD_OPTS = cd $(TOPDIR)/../bazel-bin && LD_LIBRARY_PATH=$(LD_PATH) ASIC_MOCK_MODE=1 WS_TOP=$(TOPDIR)/../../.. HAL_CONFIG_PATH=$(CONFIG_PATH) COVFILE=$(COVFILE)
PD_CMD_OPTS = cd $(TOPDIR)/../bazel-bin && LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):$(TOPDIR)/../bazel-bin/nic/sdk/model_sim/ ASIC_MOCK_MODE=1 LD_PRELOAD=$(TOPDIR)/../bazel-bin/nic/hal/pd/utils/p4pd_mock/libp4pd_mock.so HAL_CONFIG_PATH=$(TOPDIR)/conf
run-agent_api_test: $(GEN_TEST_RESULTS_DIR)/.dir
	$(CMD_OPTS) ./nic/utils/agent_api/test/agent_api_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/agent_api_test.xml"

# make target to run a specific gtest
# usage: make run-gtest target=./nic/hal/plugins/sfw/sfw_test
run-gtest: $(GEN_TEST_RESULTS_DIR)/.dir
	$(CMD_OPTS) $(GDB) $(target)

run-gtests: $(GEN_TEST_RESULTS_DIR)/.dir
	# PI gtests
	$(CMD_OPTS) ./nic/linkmgr/test/gtests/port_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/port_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/ipsec_policy_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/ipsec_policy_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/tcp_proxy_policy_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/tcp_proxy_policy_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/acl_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/acl_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/bm_allocator_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/bm_allocator_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/enicif_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/enicif_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/lif_manager_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/lif_manager_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/lif_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/lif_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/session_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/session_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/tlscb_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/tlscb_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/uplinkif_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/uplinkif_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/uplinkpc_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/uplinkpc_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/internal_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/internal_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/endpoint_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/endpoint_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/network_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/network_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/vrf_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/vrf_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/l2seg_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/l2seg_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/ipsec_sa_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/ipsec_sa_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/multicast_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/multicast_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/tunnelif_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/tunnelif_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/nwsec_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nwsec_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/scheduler_tx_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/scheduler_tx_test.xml"
	$(CMD_OPTS) $(SNORT_CMD_OPTS) ./nic/hal/test/gtests/appid_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/appid_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/qos_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/qos_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/copp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/copp_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/nh_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nh_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/route_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/route_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/nat_pool_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nat_pool_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/nat_policy_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nat_policy_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/nwsec_prof_upgrade_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nwsec_prof_upgrade_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/vrf_upgrade_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/vrf_upgrade_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/filter_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/filter_test.xml"
	$(CMD_OPTS) ./nic/hal/test/gtests/mgmt_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/mgmt_test.xml"
	@# FTE Plugins
	$(CMD_OPTS) ./nic/hal/plugins/eplearn/dpkt_learn_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/dpkt_learn_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/eplearn/arp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/arp_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/eplearn/dhcp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/dhcp_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/eplearn/learn_mix_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/learn_mix_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_utils/alg_utils_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_utils_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_rpc/alg_rpc_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_rpc_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_tftp/alg_tftp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_tftp_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_ftp/alg_ftp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_ftp_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_rtsp/alg_rtsp_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_rtsp_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/alg_dns/alg_dns_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/alg_dns_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/sfw/nwsec_policy_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/nwsec_policy_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/telemetry/telemetry_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/telemetry_test.xml"
	$(CMD_OPTS) ./nic/hal/plugins/network/network_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/network_test.xml"
	$(CMD_OPTS) ./nic/fte/fte_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/fte_test.xml"
	$(CMD_OPTS) ./nic/utils/agent_api/test/agent_api_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/agent_api_test.xml"
	@# PI Utils gtests
	cd $(TOPDIR)/../bazel-bin && ./nic/utils/bitmap/bitmap_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/bitmap_test.xml"
	cd $(TOPDIR)/../bazel-bin && ./nic/utils/host_mem/host_mem_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/host_mem_test.xml"
	cd $(TOPDIR)/../bazel-bin && ./nic/utils/pt/pt_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/pt_test.xml"
	cd $(TOPDIR)/../bazel-bin && ./nic/utils/block_list/block_list_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/block_list_test.xml"
	cd $(TOPDIR)/../bazel-bin && ./nic/utils/fsm/fsm_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/fsm_test.xml"
	@# PD Utils gtests
	$(PD_CMD_OPTS) ./nic/hal/pd/utils/acl_tcam/acl_tcam_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/acl_tcam_test.xml"
	@# Removed because of randomization
	cd $(TOPDIR)/../bazel-bin && LD_PRELOAD=$(TOPDIR)/../bazel-bin/nic/hal/pd/utils/p4pd_mock/libp4pd_mock.so HAL_CONFIG_PATH=$(TOPDIR)/conf ./nic/hal/pd/utils/flow/flow_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/flow.xml"
	$(PD_CMD_OPTS) ./nic/hal/pd/utils/met/met_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/met_test.xml"
	@# PD gtests
	$(PD_CMD_OPTS) ./nic/hal/pd/iris/test/rw_tbl_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/rw_tbl_test.xml"
	$(PD_CMD_OPTS) ./nic/hal/pd/iris/test/tnnl_rw_tbl_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/tnnl_rw_tbl_test.xml"
	@# SDK tests
	@find sdk/bazel-bin/test -name *.runfiles_manifest* | sed 's/\.runfiles_manifest$$//1' | \
	while read i; \
		do printf "\nRunning $$i\n" && $$i --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/$(basename($$i)).xml"; \
	done \

#################################################
#################### GTESTS #####################
#################################################

nic-mgr-app:
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/test:nic_mgr_app

hal-tests:
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/test:hal_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/test:hal_scale_test

gtests-common:
	# PI gtests
	$(MAKE) hal-tests
	$(MAKE) nic-mgr-app
	# PI Utils
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/bitmap:bitmap_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/host_mem:host_mem_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/pt:pt_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/block_list:block_list_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/linkmgr/test/gtests:port_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/network:network_test
	# PD Utils
	# TODO: Please enable after PD cleanup commit
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/pd/utils/acl_tcam:acl_tcam_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/pd/utils/flow:flow_test
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/pd/utils/met:met_test
	# PD
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/pd/iris/test:all
	# SDK Tests
	$(MAKE) -C $(TOPDIR)/sdk build-test

gtests: gtests-common
    ifneq ($(ARCH),aarch64)
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) --build_tag_filters=-gft,-apollo //nic/hal/test/gtests:all
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/agent_api/test:agent_api_test
		# TODO: Revisit
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/eplearn:dhcp_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/eplearn:arp_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/eplearn:dpkt_learn_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/eplearn:learn_mix_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_utils:alg_utils_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_rpc:alg_rpc_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_rtsp:alg_rtsp_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_tftp:alg_tftp_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_ftp:alg_ftp_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw/alg_dns:alg_dns_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/sfw:nwsec_policy_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/plugins/telemetry:telemetry_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/utils/fsm:fsm_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/fte:fte_test
    endif

sanity-tests:
    ifneq ($(ARCH),aarch64)
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //platform/src/app/nicmgrd/src:nicmgrd
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //platform/src/sim/model_server:model_server
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //dol/iris/test/storage:storage_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //dol/iris/test/offload:offload_test
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/e2etests/proxy:all
		#This is temporary, will be removed soon.
		bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/e2etests:all
    endif

package-tests:
	$(MAKE) hal-tests
	$(MAKE) nic-mgr-app
	$(MAKE) -C $(TOPDIR) heimdall

tests: gtests sanity-tests gtests-iris-c

gtests-iris-c:
    ifneq ($(ARCH),aarch64)
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/hal/iris-c/gtest:all
    endif

#################################################
#################### LINKMGR ####################
#################################################
linkmgr-tests:
	bazel $(BZL_OPT) build $(BZL_BLD_OPT) //nic/linkmgr/test:port_client

