# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">=1.9.5"

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

NAPLES_VER = "v1"
NAPLES_IMAGE = "naples:#{NAPLES_VER}"
NAPLES_IMAGE_FILE = "naples-docker-#{NAPLES_VER}.tgz"
NAPLES_DATA_DIR = "/var/run/naples/"
AGENT_PORT=9007

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  NODE_COUNT.times do |i|
    config.vm.define "node#{i+1}" do |subconfig|
      subconfig.vm.hostname = "node#{i+1}"

      # vm to vm internal network (eth1)
      subconfig.vm.network :private_network, virtualbox__intnet: "pen-net"

      # hostonly network (eth2)
      subconfig.vm.network :private_network, ip: "192.168.10.#{i+11}"

      #agent port forwarding
      subconfig.vm.network  "forwarded_port", guest: AGENT_PORT, host: 9000+i+11

      # Copy postman scripts
      subconfig.vm.provision "file",
                             source: "SF-Kingdom#{i+1}.postman_collection.json",
                             destination: "$HOME/postman_collection.json"
      subconfig.vm.provision "file",
                             source: "postman_env.json",
                             destination: "$HOME/postman_env.json"
    end
  end
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2096"
     vb.cpus = 2
     vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
  end

  #install docker
  config.vm.provision "docker" do |d|
    d.pull_images "networkstatic/iperf3"
  end

  # one time setup
  config.vm.provision "shell", inline: <<-SCRIPT
      yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      yum install -y bridge-utils tcpdump net-tools nodejs npm
      npm install -g newman
      mkdir -p #{NAPLES_DATA_DIR}
      docker images purge
      docker rmi -f #{NAPLES_IMAGE}
      docker load --input /vagrant/#{NAPLES_IMAGE_FILE}
  SCRIPT

  # bringup naples container
  config.vm.provision "docker" do |d|
    d.run "naples-sim", image: NAPLES_IMAGE, 
          args: "--privileged -p #{AGENT_PORT}:#{AGENT_PORT} --mount type=bind,source=#{NAPLES_DATA_DIR},target=/naples/data"
  end

  # Run this on every boot
  config.vm.provision "shell", path: "bootstrap.sh", run: 'always'
  
end
