# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "centos/7"
NODE_COUNT = 2

NAPLES_VER = "v1"
NAPLES_IMAGE = "naples:#{NAPLES_VER}"
NAPLES_IMAGE_FILE = "naples-docker-#{NAPLES_VER}.tgz"
NAPLES_INSTALL_DIR = "/var/naples/#{NAPLES_VER}"
AGENT_PORT=9007

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  NODE_COUNT.times do |i|
    config.vm.define "node#{i+1}" do |subconfig|
      subconfig.vm.hostname = "node#{i+1}"
      subconfig.vm.network :private_network, auto_config: false,
                           ip: "10.11.11.#{i+11}" # ip not used (just to make vagrant happy)
    end
  end
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2096"
     vb.cpus = 4
  end

  #install docker
  config.vm.provision "docker"

  # one time setup
  config.vm.provision "shell", inline: "yum install -y bridge-utils tcpdump"
  config.vm.provision "shell", inline: "mkdir -p #{NAPLES_INSTALL_DIR}"
  config.vm.provision "shell", inline: "docker images purge"
  config.vm.provision "shell", inline: "docker rmi -f #{NAPLES_IMAGE}"
  config.vm.provision "shell", inline: "docker load --input /vagrant/#{NAPLES_IMAGE_FILE}"

  # bringup naples container
  config.vm.provision "docker" do |d|
    d.run "naples-sim", image: NAPLES_IMAGE, 
          args: "--privileged -p #{AGENT_PORT}:#{AGENT_PORT} --mount type=bind,source=#{NAPLES_INSTALL_DIR},target=/naples/data"
  end

  # Run this on every boot
  config.vm.provision "shell", path: "bootstrap.sh", run: 'always'
  
end
