#define LPM_S0_KEYS_PER_TABLE    (15)
#define LPM_S1_KEYS_PER_TABLE    (15)
#define LPM_S2_KEYS_PER_TABLE    (7)

#define LPM_S0_TABLE_SIZE        ((LPM_KEY_SIZE*LPM_S0_KEYS_PER_TABLE)+\
                                  LPM_S0_ENTRY_PAD)
#define LPM_S0_STAGE_SIZE        (LPM_S0_TABLE_SIZE)

#define LPM_S1_ADDR_OFFSET       (LPM_S0_STAGE_SIZE)
#define LPM_S1_TABLES_PER_STAGE  (LPM_S0_KEYS_PER_TABLE+1)
#define LPM_S1_TABLE_SIZE        ((LPM_KEY_SIZE*LPM_S1_KEYS_PER_TABLE)+\
                                  LPM_S1_ENTRY_PAD)
#define LPM_S1_STAGE_SIZE        (LPM_S1_TABLE_SIZE*LPM_S1_TABLES_PER_STAGE)

#define LPM_S2_ADDR_OFFSET       (LPM_S1_ADDR_OFFSET+LPM_S1_STAGE_SIZE)
#define LPM_S2_TABLES_PER_STAGE  (LPM_S1_TABLES_PER_STAGE*\
                                 (LPM_S1_KEYS_PER_TABLE+1))
#define LPM_S2_TABLE_SIZE        ((LPM_KEY_SIZE*LPM_S2_KEYS_PER_TABLE)+\
                                  (LPM_DATA_SIZE*(LPM_S2_KEYS_PER_TABLE+1))+\
                                  LPM_S2_ENTRY_PAD)
#define LPM_S2_STAGE_SIZE        (LPM_S2_TABLE_SIZE*LPM_S2_TABLES_PER_STAGE)
#define LPM_S2_BLOCK_SIZE        (LPM_S2_TABLE_SIZE*(LPM_S1_KEYS_PER_TABLE+1))

#define LPM_S0_B0_OFFSET         (LPM_S1_ADDR_OFFSET+(0*LPM_S1_TABLE_SIZE))
#define LPM_S0_B1_OFFSET         (LPM_S1_ADDR_OFFSET+(1*LPM_S1_TABLE_SIZE))
#define LPM_S0_B2_OFFSET         (LPM_S1_ADDR_OFFSET+(2*LPM_S1_TABLE_SIZE))
#define LPM_S0_B3_OFFSET         (LPM_S1_ADDR_OFFSET+(3*LPM_S1_TABLE_SIZE))
#define LPM_S0_B4_OFFSET         (LPM_S1_ADDR_OFFSET+(4*LPM_S1_TABLE_SIZE))
#define LPM_S0_B5_OFFSET         (LPM_S1_ADDR_OFFSET+(5*LPM_S1_TABLE_SIZE))
#define LPM_S0_B6_OFFSET         (LPM_S1_ADDR_OFFSET+(6*LPM_S1_TABLE_SIZE))
#define LPM_S0_B7_OFFSET         (LPM_S1_ADDR_OFFSET+(7*LPM_S1_TABLE_SIZE))
#define LPM_S0_B8_OFFSET         (LPM_S1_ADDR_OFFSET+(8*LPM_S1_TABLE_SIZE))
#define LPM_S0_B9_OFFSET         (LPM_S1_ADDR_OFFSET+(9*LPM_S1_TABLE_SIZE))
#define LPM_S0_B10_OFFSET        (LPM_S1_ADDR_OFFSET+(10*LPM_S1_TABLE_SIZE))
#define LPM_S0_B11_OFFSET        (LPM_S1_ADDR_OFFSET+(11*LPM_S1_TABLE_SIZE))
#define LPM_S0_B12_OFFSET        (LPM_S1_ADDR_OFFSET+(12*LPM_S1_TABLE_SIZE))
#define LPM_S0_B13_OFFSET        (LPM_S1_ADDR_OFFSET+(13*LPM_S1_TABLE_SIZE))
#define LPM_S0_B14_OFFSET        (LPM_S1_ADDR_OFFSET+(14*LPM_S1_TABLE_SIZE))
#define LPM_S0_B15_OFFSET        (LPM_S1_ADDR_OFFSET+(15*LPM_S1_TABLE_SIZE))

#define LPM_S2_BLOCK0_OFFSET     (LPM_S2_ADDR_OFFSET+(0*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B0_OFFSET))
#define LPM_S2_BLOCK1_OFFSET     (LPM_S2_ADDR_OFFSET+(1*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B1_OFFSET))
#define LPM_S2_BLOCK2_OFFSET     (LPM_S2_ADDR_OFFSET+(2*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B2_OFFSET))
#define LPM_S2_BLOCK3_OFFSET     (LPM_S2_ADDR_OFFSET+(3*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B3_OFFSET))
#define LPM_S2_BLOCK4_OFFSET     (LPM_S2_ADDR_OFFSET+(4*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B4_OFFSET))
#define LPM_S2_BLOCK5_OFFSET     (LPM_S2_ADDR_OFFSET+(5*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B5_OFFSET))
#define LPM_S2_BLOCK6_OFFSET     (LPM_S2_ADDR_OFFSET+(6*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B6_OFFSET))
#define LPM_S2_BLOCK7_OFFSET     (LPM_S2_ADDR_OFFSET+(7*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B7_OFFSET))
#define LPM_S2_BLOCK8_OFFSET     (LPM_S2_ADDR_OFFSET+(8*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B8_OFFSET))
#define LPM_S2_BLOCK9_OFFSET     (LPM_S2_ADDR_OFFSET+(9*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B9_OFFSET))
#define LPM_S2_BLOCK10_OFFSET    (LPM_S2_ADDR_OFFSET+(10*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B10_OFFSET))
#define LPM_S2_BLOCK11_OFFSET    (LPM_S2_ADDR_OFFSET+(11*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B11_OFFSET))
#define LPM_S2_BLOCK12_OFFSET    (LPM_S2_ADDR_OFFSET+(12*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B12_OFFSET))
#define LPM_S2_BLOCK13_OFFSET    (LPM_S2_ADDR_OFFSET+(13*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B13_OFFSET))
#define LPM_S2_BLOCK14_OFFSET    (LPM_S2_ADDR_OFFSET+(14*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B14_OFFSET))
#define LPM_S2_BLOCK15_OFFSET    (LPM_S2_ADDR_OFFSET+(15*LPM_S2_BLOCK_SIZE)-\
                                 (LPM_S0_B15_OFFSET))

#define LPM_S1_B0_OFFSET         (0*LPM_S2_TABLE_SIZE)
#define LPM_S1_B1_OFFSET         (1*LPM_S2_TABLE_SIZE)
#define LPM_S1_B2_OFFSET         (2*LPM_S2_TABLE_SIZE)
#define LPM_S1_B3_OFFSET         (3*LPM_S2_TABLE_SIZE)
#define LPM_S1_B4_OFFSET         (4*LPM_S2_TABLE_SIZE)
#define LPM_S1_B5_OFFSET         (5*LPM_S2_TABLE_SIZE)
#define LPM_S1_B6_OFFSET         (6*LPM_S2_TABLE_SIZE)
#define LPM_S1_B7_OFFSET         (7*LPM_S2_TABLE_SIZE)
#define LPM_S1_B8_OFFSET         (8*LPM_S2_TABLE_SIZE)
#define LPM_S1_B9_OFFSET         (9*LPM_S2_TABLE_SIZE)
#define LPM_S1_B10_OFFSET        (10*LPM_S2_TABLE_SIZE)
#define LPM_S1_B11_OFFSET        (11*LPM_S2_TABLE_SIZE)
#define LPM_S1_B12_OFFSET        (12*LPM_S2_TABLE_SIZE)
#define LPM_S1_B13_OFFSET        (13*LPM_S2_TABLE_SIZE)
#define LPM_S1_B14_OFFSET        (14*LPM_S2_TABLE_SIZE)
#define LPM_S1_B15_OFFSET        (15*LPM_S2_TABLE_SIZE)
