#define SACL_SPORT_TABLE_SIZE             2112       // 64+(32*64)
#define SACL_SPORT_TREE_MAX_NODES         511        // (31 + 32 * 15)
#define SACL_SPORT_TREE_MAX_CLASSES       128
#define SACL_IPV4_TABLE_SIZE              17472      // 64+(16*64)+(16*16*64)
#define SACL_IPV6_TABLE_SIZE              87360    // 64+(64*4)+(64*16)+(64*64)+(64*256)+(64*1024)
#define SACL_IPV4_TREE_MAX_NODES          2047       // for 1023 prefixes
                                                     // 15 + (16 * 15) + (256 * 7)
#define SACL_IPV4_TREE_MAX_CLASSES        1024
#define SACL_PROTO_DPORT_TABLE_SIZE       17472      // 64+(16*64)+(16*16*64)
#define SACL_PROTO_DPORT_TREE_MAX_NODES   2047       // for 1023 "prefixes"
                                                     // 15 + (16 * 15) + (256 * 7)
#define SACL_PROTO_DPORT_TREE_MAX_CLASSES 256
#define SACL_P1_TABLE_NUM_ENTRIES         (1 << 17)  // (2^10 * 2^7)
#define SACL_P1_TABLE_SIZE                164544     // round64((1<<17)*(64/51))
#define SACL_P1_ENTRY_SIZE                10         // size in bits
#define SACL_P1_ENTRIES_PER_CACHE_LINE    51         // 51 entries of 10 bits
                                                     // each, 2 pad bits = 512 bits
#define SACL_P1_MAX_CLASSES               1024
#define SACL_P2_TABLE_NUM_ENTRIES         (1 << 18)  // (2^10 * 2^8)
#define SACL_P2_TABLE_SIZE                65536      // ((1 << 18)*2)/8
#define SACL_P2_ENTRY_SIZE                2          // entry size in bits
#define SACL_P2_ENTRIES_PER_CACHE_LINE    256        // 256 entries of 2 bits
                                                     // each = 512 bits

#define SACL_SPORT_TABLE_OFFSET         0
#define SACL_IPV4_TABLE_OFFSET          (SACL_SPORT_TABLE_SIZE)
#define SACL_PROTO_DPORT_TABLE_OFFSET  \
    (SACL_IPV4_TABLE_OFFSET + SACL_IPV4_TABLE_SIZE)
#define SACL_P1_TABLE_OFFSET           \
    (SACL_PROTO_DPORT_TABLE_OFFSET + SACL_PROTO_DPORT_TABLE_SIZE)
#define SACL_P2_TABLE_OFFSET           \
    (SACL_P1_TABLE_OFFSET + SACL_P1_TABLE_SIZE)
#define SACL_IPV6_TABLE_OFFSET         \
    (SACL_P2_TABLE_OFFSET + SACL_P2_TABLE_SIZE)

/*****************************************************************************/
/* sport related details                                                     */
/*****************************************************************************/
#define SACL_SPORT_KEY_SIZE                     (2)
#define SACL_SPORT_DATA_SIZE                    (2)
#define SACL_SPORT_S0_KEYS_PER_TABLE_ENTRY      (31)
#define SACL_SPORT_S1_KEYS_PER_TABLE_ENTRY      (15)

#if 0
#define SACL_SPORT_S0_TABLE_SIZE \
    (SACL_SPORT_KEY_SIZE*SACL_SPORT_S0_KEYS_PER_TABLE_ENTRY)
#define SACL_SPORT_S1_TABLE_SIZE \
    ((SACL_SPORT_KEY_SIZE*SACL_SPORT_S1_KEYS_PER_TABLE_ENTRY)+\
     (SACL_SPORT_DATA_SIZE*(SACL_SPORT_S1_KEYS_PER_TABLE_ENTRY+1)))
#endif

#define SACL_SPORT_S0_TABLE_SIZE        (64)
#define SACL_SPORT_S1_TABLE_SIZE        (64)
#define SACL_SPORT_S1_ADDR_OFFSET       (SACL_SPORT_S0_TABLE_SIZE)

#define SACL_SPORT_S1_B0_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(0*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B1_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(1*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B2_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(2*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B3_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(3*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B4_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(4*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B5_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(5*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B6_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(6*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B7_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(7*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B8_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(8*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B9_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(9*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B10_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(10*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B11_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(11*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B12_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(12*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B13_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(13*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B14_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(14*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B15_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(15*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B16_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(16*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B17_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(17*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B18_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(18*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B19_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(19*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B20_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(20*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B21_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(21*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B22_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(22*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B23_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(23*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B24_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(24*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B25_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(25*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B26_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(26*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B27_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(27*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B28_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(28*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B29_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(29*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B30_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(30*SACL_SPORT_S1_TABLE_SIZE))
#define SACL_SPORT_S1_B31_OFFSET \
    (SACL_SPORT_S1_ADDR_OFFSET+(31*SACL_SPORT_S1_TABLE_SIZE))
