#define SLACL_SPORT_TABLE_SIZE          2112        // 64+(32*64)
#define SLACL_IPV4_TABLE_SIZE           17472       // 64+(16*64)+(16*16*64)
#define SLACL_PROTO_DPORT_TABLE_SIZE    17472       // 64+(16*64)+(16*16*64)
#define SLACL_P1_TABLE_SIZE             164544      // round64((1<<17)*(64/51))
#define SLACL_P2_TABLE_SIZE             65536       // ((1 << 18)*2)/8

#define SLACL_SPORT_TABLE_OFFSET        0
#define SLACL_IPV4_TABLE_OFFSET         (SLACL_SPORT_TABLE_SIZE)
#define SLACL_PROTO_DPORT_TABLE_OFFSET  \
    (SLACL_IPV4_TABLE_OFFSET + SLACL_IPV4_TABLE_SIZE)
#define SLACL_P1_TABLE_OFFSET           \
    (SLACL_PROTO_DPORT_TABLE_OFFSET + SLACL_PROTO_DPORT_TABLE_SIZE)
#define SLACL_P2_TABLE_OFFSET           \
    (SLACL_P1_TABLE_OFFSET + SLACL_P1_TABLE_SIZE)

/*****************************************************************************/
/* sport related details                                                     */
/*****************************************************************************/
#define SLACL_SPORT_KEY_SIZE                    (2)
#define SLACL_SPORT_DATA_SIZE                   (2)
#define SLACL_SPORT_S0_KEYS_PER_TABLE_ENTRY     (31)
#define SLACL_SPORT_S1_KEYS_PER_TABLE_ENTRY     (15)

#if 0
#define SLACL_SPORT_S0_TABLE_SIZE \
    (SLACL_SPORT_KEY_SIZE*SLACL_SPORT_S0_KEYS_PER_TABLE_ENTRY)
#define SLACL_SPORT_S1_TABLE_SIZE \
    ((SLACL_SPORT_KEY_SIZE*SLACL_SPORT_S1_KEYS_PER_TABLE_ENTRY)+\
     (SLACL_SPORT_DATA_SIZE*(SLACL_SPORT_S1_KEYS_PER_TABLE_ENTRY+1)))
#endif

#define SLACL_SPORT_S0_TABLE_SIZE       (64)
#define SLACL_SPORT_S1_TABLE_SIZE       (64)
#define SLACL_SPORT_S1_ADDR_OFFSET      (SLACL_SPORT_S0_TABLE_SIZE)

#define SLACL_SPORT_S1_B0_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(0*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B1_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(1*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B2_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(2*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B3_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(3*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B4_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(4*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B5_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(5*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B6_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(6*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B7_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(7*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B8_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(8*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B9_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(9*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B10_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(10*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B11_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(11*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B12_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(12*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B13_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(13*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B14_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(14*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B15_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(15*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B16_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(16*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B17_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(17*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B18_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(18*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B19_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(19*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B20_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(20*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B21_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(21*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B22_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(22*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B23_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(23*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B24_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(24*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B25_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(25*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B26_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(26*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B27_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(27*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B28_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(28*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B29_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(29*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B30_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(30*SLACL_SPORT_S1_TABLE_SIZE))
#define SLACL_SPORT_S1_B31_OFFSET \
    (SLACL_SPORT_S1_ADDR_OFFSET+(31*SLACL_SPORT_S1_TABLE_SIZE))
