package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpciemgr_hdrs",
    hdrs = [
        "pciemgr.hpp",
    ],
    include_prefix = "platform/src/lib/pciemgr/include",
)

