---
version: 2.0
targets:
  apollo/aarch64build:
    commands: ["make", "PIPELINE=apollo", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:avinash@pensando.io"]
    area:
    sub-area:
    feature:

  artemis/aarch64_build:
    commands: ["make", "PIPELINE=artemis", "ARCH=aarch64", "PLATFORM=hw"]
    owners: ["email:saratk@pensando.io","email:srikanth@pensando.io"]
    area:
    sub-area:
    feature:

  artemis/pds_scale_test_mock:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/pds_scale_test_mock"]
    owners: ["email:saratk@pensando.io", "email:vijasrin@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

  artemis/ftlite:
    commands: ["make", "PIPELINE=artemis", "jobd/artemis/ftlite"]
    owners: ["email:avinash@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-artemis-x86

image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /usr/src/github.com/pensando/sw/nic/nic_sanity_logs.tar.gz
