package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpciehdevices_hdrs",
    hdrs = [
        "pciehdevices.h",
    ],
    include_prefix = "platform/src/lib/pciehdevices/include",
)

