package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "mtrack",
    hdrs = glob(["*.hpp"]),
    deps = [
        "//nic/include:base_includes",
    ],
)
