package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "bm_allocator",
    srcs = [
        "bm_allocator.cc",
        "bm_allocator.hpp",
    ],
    hdrs = ["bm_allocator.hpp"],
    deps = [
        "//nic/include:base_includes",
        "//nic/third-party/spdlog",
    ],
)
