#
# Copyright (c) 2017, Pensando Systems Inc.
#

LIBRARY = libmisc.a libmisc.so
SOURCES = \
	hex_format.c \
	maclib.c \
	strncpy0.c \
	strtoargv.c \
	$(NULL)

LCFLAGS += -I ../include

TOPDIR = ../../../..
include $(TOPDIR)/make/Makefile.inc
