// {C} Copyright 2020 Pensando Systems Inc. All rights reserved

#ifndef __ELBA_BARCO_H__
#define __ELBA_BARCO_H__

#define ELBA_BARCO_SYM_REQ_DESC_SZ_SHIFT               7
#define ELBA_BARCO_SYM_REQ_DESC_SZ                     (1 << ELBA_BARCO_SYM_REQ_DESC_SZ_SHIFT)

#define ELBA_BARCO_GCM_DECRYPT_BUG_REQ_STRIDE_SHIFT    3
#define ELBA_BARCO_GCM_DECRYPT_BUG_REQ_STRIDE          (1 << ELBA_BARCO_GCM_DECRYPT_BUG_REQ_STRIDE_SHIFT)
#define ELBA_BARCO_GCM_DECRYPT_BUG_REQ_STRIDE_MASK     ((1 << ELBA_BARCO_GCM_DECRYPT_BUG_REQ_STRIDE_SHIFT) - 1)

#define ELBA_BARCO_MD_HENS_REG_BASE                    (0x6580000)

#define ELBA_BARCO_MD_HENS_REG_GCM0_PRODUCER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x20c)
#define ELBA_BARCO_MD_HENS_REG_GCM0_CONSUMER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x280)

#define ELBA_BARCO_MD_HENS_REG_GCM1_PRODUCER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x30c)
#define ELBA_BARCO_MD_HENS_REG_GCM1_CONSUMER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x380)

#define ELBA_BARCO_MD_HENS_REG_XTS0_PRODUCER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0xc)
#define ELBA_BARCO_MD_HENS_REG_XTS0_CONSUMER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x80)

#define ELBA_BARCO_MD_HENS_REG_XTS1_PRODUCER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x10c)
#define ELBA_BARCO_MD_HENS_REG_XTS1_CONSUMER_IDX       (ELBA_BARCO_MD_HENS_REG_BASE + 0x180)

#define ELBA_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM0        (ELBA_BARCO_MD_HENS_REG_BASE + 0x2000)
#define ELBA_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM1        (ELBA_BARCO_MD_HENS_REG_BASE + 0x2200)
#define ELBA_BARCO_MD_HENS_REG_DRBG_PSNL_STR           (ELBA_BARCO_MD_HENS_REG_BASE + 0x2400)
#define ELBA_BARCO_MD_HENS_REG_DRBG_ENTROPY_INST       (ELBA_BARCO_MD_HENS_REG_BASE + 0x2440)
#define ELBA_BARCO_MD_HENS_REG_DRBG_ENTROPY_RESEED     (ELBA_BARCO_MD_HENS_REG_BASE + 0x2480)
#define ELBA_BARCO_MD_HENS_REG_DRBG_ISR                (ELBA_BARCO_MD_HENS_REG_BASE + 0x2500)
#define ELBA_BARCO_MD_HENS_REG_DRBG_MSK                (ELBA_BARCO_MD_HENS_REG_BASE + 0x2504)
#define ELBA_BARCO_MD_HENS_REG_DRBG_ICR                (ELBA_BARCO_MD_HENS_REG_BASE + 0x2508)
#define ELBA_BARCO_MD_HENS_REG_DRBG_VER                (ELBA_BARCO_MD_HENS_REG_BASE + 0x250c)
#define ELBA_BARCO_MD_HENS_REG_DRBG_GCT                (ELBA_BARCO_MD_HENS_REG_BASE + 0x2510)
#define ELBA_BARCO_MD_HENS_REG_DRBG_RSVR0              (ELBA_BARCO_MD_HENS_REG_BASE + 0x2514)
#define ELBA_BARCO_MD_HENS_REG_DRBG_GS                 (ELBA_BARCO_MD_HENS_REG_BASE + 0x2518)
#define ELBA_BARCO_MD_HENS_REG_DRBG_RSVR1              (ELBA_BARCO_MD_HENS_REG_BASE + 0x250c)
#define ELBA_BARCO_MD_HENS_REG_DRBG_RNG                (ELBA_BARCO_MD_HENS_REG_BASE + 0x2520)
#define ELBA_BARCO_MD_HENS_REG_DRBG_DRNGE              (ELBA_BARCO_MD_HENS_REG_BASE + 0x2524)

#define ELBA_BARCO_MP_MPNS_REG_BASE                    (0x6560000) // CAP_ADDR_BASE_MP_MPNS_OFFSET

#define ELBA_BARCO_MP_MPNS_REG_MPP1_PRODUCER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x10c)
#define ELBA_BARCO_MP_MPNS_REG_MPP1_CONSUMER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x180)

#define ELBA_BARCO_MP_MPNS_REG_MPP2_PRODUCER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x20c)
#define ELBA_BARCO_MP_MPNS_REG_MPP2_CONSUMER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x280)

#define ELBA_BARCO_MP_MPNS_REG_MPP3_PRODUCER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x30c)
#define ELBA_BARCO_MP_MPNS_REG_MPP3_CONSUMER_IDX       (ELBA_BARCO_MP_MPNS_REG_BASE + 0x380)

#define ELBA_BARCO_COMMAND_HMAC_SHA256_GENERATE        0x23200000
#define ELBA_BARCO_COMMAND_HMAC_SHA256_VERIFY          0x23300000
#define ELBA_BARCO_COMMAND_HMAC_SHA384_GENERATE        0x24200000
#define ELBA_BARCO_COMMAND_HMAC_SHA384_VERIFY          0x24300000
#define ELBA_BARCO_COMMAND_HMAC_SHA512_GENERATE        0x25200000
#define ELBA_BARCO_COMMAND_HMAC_SHA512_VERIFY          0x25300000

#define ELBA_BARCO_COMMAND_AES_CBC_ENCRYPT             0x01000000
#define ELBA_BARCO_COMMAND_AES_CBC_DECRYPT             0x01100000

#endif  /* __ELBA_BARCO_H__ */
