SERVICE_PROTOS = $(wildcard *.proto)
EXTRA_GOFAST_OUT= Mgithub.com/pensando/sw/api/protos/archive.proto=github.com/pensando/sw/api/generated/monitoring,
EXTRA_INCLUDES=-I${GOPATH}/src/github.com/pensando/sw/api/protos

include ../../../Makefile.proto