#
# Copyright (c) 2017-2018, Pensando Systems Inc.
#

SUBDIRS = \
	cfgspace \
	misc \
	nicmgr \
	hal_api \
	evutils \
	intrutils \
	nicmgr \
	pal \
	pciehdevices \
	pciemgr \
	pciemgrutils \
	pciemgr_if \
	pcieport \
	pcietlp \
	sysmgr \
	upgrade \
	$(NULL)

TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
