#
# Copyright (c) 2017, Pensando Systems Inc.
#

SUBDIRS = \
	cfgspace \
	misc \
	pciehdevices \
	pciehost \
	pciehsvc \
	pciehw \
	pcieport \
	pal \
	$(NULL)

TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
