package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libevutils_hdrs",
    hdrs = [
        "evutils.h",
    ],
    include_prefix = "platform/src/lib/evutils/include",
)

