TOPDIR = ../..
SHAREDLIBRARY = libperiodic.so

LCXXFLAGS = \
			-I. \
			-I../../include \
			-I../../third-party/spdlog/include \

SOURCES = \
		  periodic.cc \
		  $(NULL)

include $(TOPDIR)/make/Makefile.inc
