package(default_visibility = ["//visibility:public"])

load("//nic/delphi/compiler:delphi.bzl", "delphi_compile")

# compile the proto file
delphi_compile(
    name = "upgrade_gen",
    srcs = [ 'upgrade.proto' ],
)
