---
version: 2.0
targets:
  gtests:
    commands: ["make", "jobd/gtests"]
    owners: ["email:saratk@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
    - build-iris-x86-elba
  halctl:
    commands: ["make", "jobd/halctl"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86

  # ====================== ARM Tests ===========================
  arm/build:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && cd nic && V=1 make ARCH=aarch64 PIPELINE=iris PLATFORM=hw"]
    owners: ["email:dbarsky@pensando.io"]
    area:
    sub-area:
    feature:
  arm/build/haps:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && cd nic && V=1 make ARCH=aarch64 PIPELINE=iris PLATFORM=haps package-haps-dbg"]
    owners: ["email:dbarsky@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== Storage Tests ===========================
  storage:
    commands: ["make", "jobd/storage"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  storage/perf:
    commands: ["make", "jobd/storage/perf"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  storage/nvme:
    commands: ["make", "jobd/storage/nvme"]
    owners: ["email:piraman@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  #storage/nvme_perf:
  # commands: ["make", "jobd/storage/nvme_perf"]
  # owners: ["email:piraman@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #storage/nicmgr:
  #  commands: ["make", "jobd/storage/nicmgr"]
  #  owners: ["email:piraman@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #Test running into locking issues - disabling for now
  #storage/combined:
  # commands: ["make", "jobd/storage/combined"]
  # owners: ["email:piraman@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ======== A limited # of HAL Tests can be run from jobd ========
  hal_test_fips/rsa-siggen15-0:
    commands: ["make", "jobd/hal_test_fips/rsa-siggen15-0"]
    owners: ["email:raghava@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  # ====================== Offload Tests ===========================
  offload:
    commands: ["make", "jobd/offload"]
    owners: ["email:raghava@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86

  # ====================== Config Tests ===========================
  #configtest:
  # commands: ["make", "jobd/configtest"]
  # owners: ["email:dbarsky@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ====================== DOL Tests ===========================
  dol/rdma:
    commands: ["make", "jobd/dol/rdma"]
    owners: ["email:rdma-dpath@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/rdma_ext:
    commands: ["make", "jobd/dol/rdma_ext"]
    owners: ["email:rdma-dpath@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  # Unified Mode changes. No longer support Uplink -> Uplink
  #dol/fte:
  #  commands: ["make", "jobd/dol/fte"]
  #  owners: ["email:lseshan@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  dol/fte2:
    commands: ["make", "jobd/dol/fte2"]
    owners: ["email:lseshan@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  # Unified Mode changes. No longer support vxlan
  #dol/ftevxlan:
  #  commands: ["make", "jobd/dol/ftevxlan"]
  #  owners: ["email:lseshan@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support Uplink -> Uplink
  #dol/norm:
  #  commands: ["make", "jobd/dol/norm"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  dol/eth:
    commands: ["make", "jobd/dol/eth"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/acl:
    commands: ["make", "jobd/dol/acl"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  # Unified Mode changes. No longer support proxy
  #dol/proxy:
  #  commands: ["make", "jobd/dol/proxy"]
  #  owners: ["email:raghava@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support ipsec
  #dol/ipsec:
  #  commands: ["make", "jobd/dol/ipsec"]
  #  owners: ["email:raghava@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support Uplink -> Uplink
  #dol/networking:
  #  commands: ["make", "jobd/dol/networking"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support vxlan
  #dol/vxlan:
  #  commands: ["make", "jobd/dol/vxlan"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support mplsudp
  #dol/mplsudp:
  #  commands: ["make", "jobd/dol/mplsudp"]
  #  owners: ["email:vijasrin@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # IPSG table is moved to stage 5 of ingress. The test cases are doing span from drop_stats table
  # in stage 5, which will not work as drop is being set in same stage 5.
  # dol/ipsg:
  #   commands: ["make", "jobd/dol/ipsg"]
  #   owners: ["email:bharat@pensando.io"]
  #   area:
  #   sub-area:
  #   feature:
  #   build-dependencies:
  #   - build-iris-x86
  # Unified Mode changes. No longer support Uplink -> Uplink
  #dol/firewall:
  #  commands: ["make", "jobd/dol/firewall"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support hostpin
  #dol/pin:
  #  commands: ["make", "jobd/dol/pin"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support multicast 
  #dol/multicast:
  #  commands: ["make", "jobd/dol/multicast"]
  #  owners: ["email:ajeer@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #dol/pinl2mc:
  #  commands: ["make", "jobd/dol/pinl2mc"]
  #  owners: ["email:ajeer@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support l4lb
  #dol/l4lb:
  #  commands: ["make", "jobd/dol/l4lb"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #dol/dos:
    #commands: ["make", "jobd/dol/dos"]
    #owners: ["email:bharat@pensando.io"]
    #area:
    #sub-area:
    #feature:
  dol/recirc:
    commands: ["make", "jobd/dol/recirc"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/classic:
    commands: ["make", "jobd/dol/classic"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/classicl2mc:
    commands: ["make", "jobd/dol/classicl2mc"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/parser:
    commands: ["make", "jobd/dol/parser"]
    owners: ["email:pbhide@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/telemetry:
    commands: ["make", "jobd/dol/telemetry"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  # Unified Mode changes. No longer support p4pt
  #dol/p4pt:
  #  commands: ["make", "jobd/dol/p4pt"]
  #  owners: ["email:jainvipin@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  # Unified Mode changes. No longer support app redir
  #dol/app_redir:
  #  commands: ["make", "jobd/dol/app_redir"]
  #  owners: ["email:tuyenq@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  dol/basetopo:
    commands: ["make", "jobd/dol/basetopo"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  dol/swphv:
    commands: ["make", "jobd/dol/swphv"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86

  # ====================== GFT Tests ===========================
  #dol/gft:
  #  commands: ["make", "PIPELINE=gft", "jobd/dol/gft"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-gft-x86
  #dol/gft/rdma:
  #commands: ["make", "PIPELINE=gft", "jobd/dol/gft/rdma"]
  #  owners: ["email:rdma-dpath@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-gft-x86
  #dol/gft/rdma_l2l:
  #  commands: ["make", "PIPELINE=gft", "jobd/dol/gft/rdma_l2l"]
  #  owners: ["email:rdma-dpath@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-gft-x86
  gft/gtest:
    commands: ["make", "PIPELINE=gft", "jobd/gft/gtest"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-gft-x86

  # ====================== MBT Tests ===========================
  #mbt/base:
  #  commands: ["make", "jobd/mbt/base"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #mbt/networking:
  #  commands: ["make", "jobd/mbt/networking"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #mbt/firewall:
  #  commands: ["make", "jobd/mbt/firewall"]
  #  owners: ["email:bharat@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #mbt/alg:
  #  commands: ["make", "jobd/mbt/alg"]
  #  owners: ["email:pavramas@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86

  # ====================== Make Infra Tests ===========================
  #make/sdk:
  # commands: ["make", "jobd/make/sdk"]
  # owners: ["email:bharat@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #make/nic:
  # commands: ["make", "jobd/make/nic"]
  # owners: ["email:bharat@pensando.io"]
  # area:
  # sub-area:
  # feature:

  codesync:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make naples-firmware && make -C nic jobd/codesync"]
    owners: ["email:bharat@pensando.io"]
    area:
    sub-area:
    feature:

  # ====================== E2E DOL Tests ===========================
  #dol/e2e/tlsproxy:
  # commands: ["make", "jobd/dol/e2e/tlsproxy"]
  # owners: ["email:raghava@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #dol/e2e/tlsproxy/v6:
  # commands: ["make", "jobd/dol/e2e/v6tlsproxy"]
  # owners: ["email:raghava@pensando.io"]
  # area:
  # sub-area:
  # feature:
  # Disabling as this test failing 100% for last 10 days
  #dol/e2e/eplearn:
  #  commands: ["make", "jobd/dol/e2e/eplearn"]
  #  owners: ["email:sudhiaithal@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:
  #  build-dependencies:
  #  - build-iris-x86
  #dol/e2e/alg:
  # commands: ["make", "jobd/dol/e2e/alg"]
  # owners: ["email:pavramas@pensando.io"]
  # area:
  # sub-area:
  # feature:
  #dol/e2e/l7:
  #  commands: ["make", "jobd/dol/e2e/l7"]
  #  owners: ["email:piraman@pensando.io"]
  #  area:
  #  sub-area:
  #  feature:

  # ====================== Agent Tests ===========================
  agent:
    commands: ["make", "jobd/agent"]
    owners: ["email:abhi@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86
  e2e/naples-sim:
    commands: ["make", "jobd/e2e/naples-sim"]
    owners: ["email:sudhiaithal@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86

  # ====================== IRIS-C Tests ===========================
  # iris-c gtests
  #filter/gtest:
  # commands: ["make", "jobd/filter/gtest"]
  # owners: ["email:saratk@pensando.io"]
  # area:
  # sub-area:
  # feature:

  # ====================== Upg Mgr Tests ===========================
  upgrade_manager/gtests:
    commands: ["make", "jobd/upgrade_manager/gtests"]
    owners: ["email:arathore@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-iris-x86

  # ====================== Nic Mgr Tests ===========================
  # Failing only in jobd. Not able to reproduce locally
  #nicmgr/gtest:
  # commands: ["make", "jobd/nicmgr/gtest"]
  # owners: ["email:bharat@pensando.io"]
  # area:
  # sub-area:
  # feature:
  nicmgr/gtest_classic:
   commands: ["make", "jobd/nicmgr/gtest_classic"]
   owners: ["email:bharat@pensando.io"]
   area:
   sub-area:
   feature:
   build-dependencies:
   - build-iris-x86

  #coremgr:
  # commands: ["sh", "-c", "cd /sw && make pull-assets && cd nic && bazel build //nic/sysmgr/coremgr/... && cd /sw/nic/sysmgr/coremgr/test && ./test.sh; ret=$? ; exit $ret" ]
  # owners: ["email:dbarsky@pensando.io"]
  # area:
  # sub-area:
  # feature:

  delphi:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/sw; make ws-tools && cd nic && V=1 make PIPELINE=iris && cd delphi && make test"]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
  #upgmgr:
  # commands: ["sh", "-c", "cd /sw/nic && bazel build //nic/upgrade_manager/... && bazel test //nic/upgrade_manager/... --jobs 1 --cache_test_results=no --test_output=all" ]
  # owners: ["email:arathore@pensando.io"]
  # area:
  # sub-area:
  # feature:
  sysmgr:
    commands: ["sh", "-c", "cd /sw/nic/sysmgr/test && ./test.sh" ]
    owners: ["email:stavros@pensando.io"]
    area:
    sub-area:
    feature:
  goldfw:
    commands: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw/nic && ./tools/build_goldfw.sh" ]
    owners: ["email:dpshah@pensando.io"]
    area:
    sub-area:
    feature:
  venice:
    commands: ["sh", "-c", "cd $GOPATH/src/github.com/pensando/sw && make ws-tools && make pull-assets && cd $GOPATH/src/github.com/pensando/sw/nic VENICE_DEV=1 LD_LIBRARY_PATH=$GOPATH/src/github.com/pensando/sw/nic/build/x86_64/iris/lib/ TRACKER_URL=\"tracker.test.pensando.io\" make netagent.gobin && go test -tags iris github.com/pensando/sw/nic/agent/dscagent/pipeline/iris; ret=$? ; make sanity_logs ; exit $ret" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:

cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
  - /sw/iota/iota_sanity_logs.tar.gz


#warmd:
#  target:
#    commands: ["make", "jobd/iota/venice-sim"]
#    owners: ["email:sudhiaithal@pensando.io"]
#  create:
#    image: build-112
#    count: 6
#    resources:
#      cpus  : 8
#      memory: 20
#      pvt-networks:
#            - control
#      data-networks:
#            - data-1
#            - data-2
#  provision:
#    username: vm
#    password: vm
#    # additional vars to pass to ansible.
#    vars:
