#! /bin/bash
export DIR_NIC=`dirname $0`
export HAL_CONFIG_PATH=$DIR_NIC/conf/
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DIR_NIC/obj:$DIR_NIC/asic/capri/model/capsim-gen/lib $GDB $DIR_NIC/obj/hal -c hal.json 2>&1 | tee hal.log
