---
version: 2.0
targets:
  apulu/all-cloud-pipeline-builds:
    commands: ["echo", "cloud builds"]
    owners: ["email:kalyanbade@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apollo-x86
    - build-artemis-x86

  apulu/gtest_1:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtest_1"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/gtest_2:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/gtest_2"]
    owners: ["email:jcruz@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/vxlan:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/vxlan"]
    owners: ["email:param@pensando.io", "email:sai@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/lpm:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/lpm"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/rfc_ingress:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/rfc_ingress"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/rfc_egress:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/rfc_egress"]
    owners: ["email:ajeer@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/dol/learn:
    commands: ["make", "PIPELINE=apulu", "jobd/dol/apulu/learn"]
    owners: ["email:sunil@pensando.io", "email:kalyanbade@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/pds_scale_test_mock:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/pds_scale_test_mock"]
    owners: ["email:akoradha@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/pds_uds_testapp:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/pds_uds_testapp"]
    owners: ["email:srikanth@pensando.io" ]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/valgrind:
    # build-apulu-valgrind runs valgrind gtests and creates the file
    commands: ["sh", "-c", "while [ ! -f /tmp/apulu_gtests_valgrind.done ]; do sleep 60; done"]
    owners: ["email:sai@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-valgrind

  metaswitch/hals_test:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/metaswitch_hals_test"]
    owners: ["email:vijasrin@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  metaswitch/store_test:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/metaswitch_store_test"]
    owners: ["email:vijasrin@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

  apulu/upgrade_test:
    commands: ["make", "PIPELINE=apulu", "jobd/apulu/upgrade"]
    owners: ["email:hareesh@pensando.io"]
    area:
    sub-area:
    feature:
    build-dependencies:
    - build-apulu-x86

image:
  bind_dir: "/sw"
  work_dir: "/sw/nic"

logfiles:
  - /sw/nic/nic_sanity_logs.tar.gz
