#
# Copyright (c) 2018, Pensando Systems Inc.
#

PROGRAM = palapp
SOURCES = palapp.c

LCFLAGS = \
	-I ../../../pal/include \
	$(NULL)

LIBRARIES = \
	-lpal \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc
