#
# Copyright (c) 2017, Pensando Systems Inc.
#

LIBDIRS = libsimlib libsimdev
PGMDIRS = simd tests
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
LBUILD_ARCHES = x86_64

TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
