
TOPDIR = ../../../..
BUILDOBJS = xx

LCXXFLAGS = \
			-I. \
			-I.. \
			-I../tcam \
			-I../../../../include \
			-I../../../../hal/pd \
			-I../../../../gen/iris/include \
			-I../../../../third-party/spdlog/include

SOURCES = \
	acl_tcam.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
