#
# Copyright (c) 2017, Pensando Systems Inc.
#

PROGRAM = palreg
SOURCES = palreg.c

LCFLAGS = \
	-I ../../../pal/include \
	$(NULL)

LIBRARIES = \
	-lpal \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc
