# {C} Copyright 2017 Pensando Systems Inc. All rights reserved

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_test(
    name = "offload_sim_test",
    srcs = [ "offload_sim_test.cc", ],
    deps = [ "//storage/offload/src/sim:pnso_sim",
             "//:gtest" ],
    size = "small"
)
