#
# Copyright (c) 2019, Pensando Systems Inc.
#

TOPDIR = ../..
PROGRAM = pciestress
SOURCES = pciestress.c
LBUILD_ARCHES = x86_64
LCFLAGS = -I $(TOPDIR)/..
SYSTEM_LIBRARIES = /lib/x86_64-linux-gnu/libpci.so.3

include $(TOPDIR)/make/Makefile.inc
