package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "platformcommon_hdrs",
    hdrs = [
        "pci_ids.h",
    ],
    include_prefix = "platform/include/common",
)

