package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libintrutils_hdrs",
    hdrs = [
        "intrutils.h",
    ],
    include_prefix = "platform/src/lib/intrutils/include",
)

