#!/bin/sh

# /usr/pensando/bin of host (or VM) is mapped to /home/usr/pensando/bin inside the base container.
# The binaries (which need to be run on the host) are packaged in the base container.
# Steps below copy the binaries to be run on the host.
#   Also any config files are copied here too.
#  Please note that binaries must be Static binaries (hence we dont have to worry about presence of dynamic libraries on host)
mv -f /target/usr/bin/systemd-docker /host/usr/pensando/bin/systemd-docker
mv -f /target/usr/bin/kubelet /host/usr/pensando/bin/kubelet
mv -f /target/usr/lib/systemd/system/* /host/usr/lib/systemd/system/
# Each component gets an individual subdir under /etc/pensando if needed.
# The subdir name for each component must match the definitions in venice/globals/modules.go.
# Subdir is created here so that it already exists when the container start and it needs to be mounted.
# No component should mount /etc/pensando except CMD.
# /etc/pensando/shared/common is shared across all components.
mkdir -p /host/etc/pensando/shared/common
mv -f /target/etc/pensando/shared/common/venice.json /host/etc/pensando/shared/common/venice.json
mv -f /target/etc/pensando/shared/common/venice.conf /host/etc/pensando/shared/common/venice.conf
mkdir -p /host/etc/pensando/pen-influx
mv -f /target/etc/pensando/pen-influx/influxdb.conf /host/etc/pensando/pen-influx/influxdb.conf
mkdir -p /host/etc/pensando/pen-apiserver
mkdir -p /host/etc/pensando/pen-cmd
mkdir -p /host/etc/pensando/pen-elastic
mkdir -p /host/etc/pensando/pen-filebeat
mkdir -p /host/etc/pensando/pen-etcd
mkdir -p /host/etc/pensando/kubernetes
mkdir -p /host/etc/pensando/pen-ntp
