#!/bin/sh

# /usr/pensando/bin of host (or VM) is mapped to /home/usr/pensando/bin inside the base container.
# The binaries (which need to be run on the host) are packaged in the base container.
# Steps below copy the binaries to be run on the host.
#   Also any config files are copied here too.
#  Please note that binaries must be Static binaries (hence we dont have to worry about presence of dynamic libraries on host)
mv -f /target/usr/bin/systemd-docker /host/usr/pensando/bin/systemd-docker
mv -f /target/usr/bin/kubelet /host/usr/pensando/bin/kubelet
mv -f /target/usr/bin/kubectl /host/usr/pensando/bin/kubectl
mv -f /target/usr/lib/systemd/system/* /host/usr/lib/systemd/system/
# Each component gets an individual subdir under /etc/pensando if needed.
# The subdir name for each component must match the definitions in venice/globals/modules.go.
# Subdir is created here so that it already exists when the container start and it needs to be mounted.
# No component should mount /etc/pensando except CMD.
# /etc/pensando/shared/common is shared across all components.
mkdir -p /host/etc/pensando/configs/shared/common
mkdir -p /host/etc/pensando/configs/pen-influx
mkdir -p /host/etc/pensando/configs/pen-apiserver
mkdir -p /host/etc/pensando/configs/pen-cmd
mkdir -p /host/etc/pensando/configs/pen-elastic
mkdir -p /host/etc/pensando/configs/pen-elastic/elastic-discovery
mkdir -p /host/etc/pensando/configs/pen-filebeat
mkdir -p /host/etc/pensando/configs/pen-etcd
mkdir -p /host/etc/pensando/configs/kubernetes
mkdir -p /host/etc/pensando/configs/kubernetes/pen-kube-apiserver
mkdir -p /host/etc/pensando/configs/kubernetes/pen-kube-scheduler
mkdir -p /host/etc/pensando/configs/kubernetes/pen-kube-controller-manager
mkdir -p /host/etc/pensando/configs/kubernetes/pen-kubelet
mkdir -p /host/etc/pensando/configs/pen-ntp
mkdir -p /host/var/log/pensando
mkdir -p /host/var/log/pensando/elastic
mkdir -p /host/var/log/pensando/filebeat
mkdir -p /host/var/lib/pensando

# We need to differentiate build time configs from the configs that get generated runt-time based on user-config
# as of now - keep a copy of the build time configs at /host/etc/pensando/configs.
# even during node cleanup we just copy from this to the expected path
cp -f /target/etc/pensando/pen-influx/influxdb.conf /host/etc/pensando/configs/pen-influx/influxdb.conf
cp -f /target/etc/pensando/shared/common/venice.json /host/etc/pensando/configs/shared/common/venice.json
cp -f /target/etc/pensando/shared/common/venice.conf /host/etc/pensando/configs/shared/common/venice.conf
cp -f /target/usr/bin/gettechsupport.sh /host/usr/pensando/bin/gettechsupport.sh


#move to directories that are expected by the various services
cp -rf /host/etc/pensando/configs/* /host/etc/pensando/

# Directories for keys and certificates
# Each component gets an individual subdir under /var/lib/pensando/pki if needed.
# The subdir name for each component must match the definitions in venice/globals/modules.go.
# Subdir is created here so that it already exists when the container start and it needs to be mounted.
# No component should mount /var/lib/pensando/pki except CMD.
mkdir -p /host/var/lib/pensando/pki/kubernetes/pen-kube-apiserver
mkdir -p /host/var/lib/pensando/pki/kubernetes/pen-kube-scheduler
mkdir -p /host/var/lib/pensando/pki/kubernetes/pen-kube-controller-manager
mkdir -p /host/var/lib/pensando/pki/kubernetes/service-accounts
mkdir -p /host/var/lib/pensando/pki/kubernetes/pen-kubelet

