
TOPDIR = ../..
SHAREDLIBRARY = libshmseg.so

LCXXFLAGS = \
			-Wno-write-strings \
			-I../../include \
			-I../../third-party/spdlog/include

SOURCES = \
	shmseg.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
