# {C} Copyright 2017 Pensando Systems Inc. All rights reserved

package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

# Slab Test
cc_test(
    name = "slab_test",
    srcs = ["slab_test.cc"],
    deps = [
        "//:gtest",
        "//:sdk_headers",
        "//obj:sdk_slab",
    ],
)
