CXX = g++
CPPFLAGS += -I/usr/local/include -std=c++11 -g -DHAL_MRL_PORT=1
OBJ_DIR = ../../../../obj
INC_DIRS = -I. -I.. -I../.. -I../../../../include -I../../../../third-party/spdlog/include
INC_DIRS += -I../../../../model_sim/include

LIBS = ''
LIB_DIR = ''

SRCS := \
    cap_top_csr.cc \
    cap_csr_base.cc \
    cap_env_base.cc \
    LogMsg.cc \
    cap_ppa_csr.cc \
    cap_prd_csr.cc \
    cap_ptd_csr.cc \
    cap_te_csr.cc \
    cap_mpu_csr.cc \
    cap_pics_csr.cc \
    cap_pxb_csr.cc \
    cap_pp_csr.cc \
    cap_npv_csr.cc \
    cap_pict_csr.cc \
    cap_txs_csr.cc \
    cap_pbc_csr.cc \
    cap_pbm_csr.cc \
    cap_wa_csr.cc \
    cap_he_csr.cc \
    cap_dpr_csr.cc \
    cap_dpp_csr.cc \
    cap_dpphdr_csr.cc \
    cap_dprstats_csr.cc \
    cap_dppstats_csr.cc \
    cap_dpphdrfld_csr.cc \
    cap_dprmem_csr.cc \
    cap_dprcfg_csr.cc \
    cap_dppcsum_csr.cc \
    cap_dprhdrfld_csr.cc \
    cap_pxp_csr.cc \
    cap_pxc_csr.cc \
    cap_dppmem_csr.cc \
    $(NULL)

OBJS := $(basename $(SRCS))
OBJS := $(OBJS:%=$(OBJ_DIR)/%.o)

all: $(OBJS)
	$(CXX) -shared -o $(OBJ_DIR)/libcaprimrl.so $(OBJS)

$(OBJ_DIR)/%.o : %.cc
	$(CXX) -L../../../../obj -L../../../../model_sim/build -lmodelclient -lcapri $(CPPFLAGS) $(INC_DIRS) -c -Wall -Werror -fpic -o $@ $<

clean:
	rm -rf $(OBJ_DIR)/cap_*csr*.o $(OBJ_DIR)/libcaprimrl.so
