#!/bin/sh

asic=${ASIC-capri}
npass=0
nfail=0
for tc in testcases/*.in; do
    tb=`basename $tc .in`
    tbexp="testcases/$asic/$tb.exp"
    tbout="testcases/$asic/$tb.out"
    rm -f $HOME/.palreg-*
    ../testtools/genrun pciemgrd < $tc > $tbout
    if ! cmp -s $tbexp $tbout; then
	printf "%-40s FAILED ***\n" $tc
	diff $tbexp $tbout
	nfail=`expr $nfail + 1`
    else
	printf "%-40s passed\n" $tc
	rm $tbout
	npass=`expr $npass + 1`
    fi
done

echo Passed: $npass Failed: $nfail
[ $nfail != 0 ] && exit 1
exit 0
