#
# Copyright (c) 2017, Pensando Systems Inc.
#

PROGRAM = pciehmgrtest
SOURCES = pciehmgrtest.c

LCFLAGS = -I ../../../pciehost/include

LIBRARIES = -lutils
SYSTEM_LIBRARIES += -lreadline

TOPDIR = ../../..
include $(TOPDIR)/make/Makefile.inc
