package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

load("//nic/bazel:common_deps.bzl", "gl_deps_list")
load("//nic/bazel:common_deps.bzl", "gl_linkopts_list")
load("//nic/bazel:common_deps.bzl", "sdk_copts")

#cc_library(
#    name = "tcam",
#    srcs = [
#        "tcam.cc",
#        "tcam.hpp",
#        "tcam_entry.cc",
#        "tcam_entry.hpp",
#    ],
#    hdrs = [
#        "tcam.hpp",
#        "tcam_entry.hpp",
#    ],
#    copts = sdk_copts,
#    deps = [
#        "@sdk//obj:sdk_indexer",
#        "//nic/hal/pd:hal_pd_includes",
#        "//nic/hal/pd/utils/acl_tcam:acl_tcam_includes",
#        "//nic/include:base_includes",
#        "//nic/third-party/spdlog",
#    ],
#)
#
#cc_library(
#    name = "tcam_includes",
#    srcs = [],
#    hdrs = [
#        "tcam.hpp",
#        "tcam_entry.hpp",
#    ],
#)
#
#cc_test(
#    name = "tcam_test",
#    srcs = ["test/tcam_test.cc"],
#    linkopts = gl_linkopts_list,
#    deps = gl_deps_list,
#    copts = sdk_copts,
#)
