
TOPDIR = ../../../..
BUILDOBJS = xx

LCXXFLAGS = \
			-I.. \
			-I../acl_tcam \
			-I../../../../include \
			-I../../../../hal/pd \
			-I../../../../gen/iris/include \
			-I../../../../third-party/spdlog/include

SOURCES = \
	tcam.cc \
	tcam_entry.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
