package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "ht",
    srcs = [
        "ht.cc",
        "ht.hpp",
    ],
    hdrs = ["ht.hpp"],
    deps = [
        "//nic/include:base_includes",
        "//nic/third-party/spdlog",
    ],
)
