# {C} Copyright 2017 Pensando Systems Inc. All rights reserved

package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

# Slab Test
cc_test(
    name = "list_test",
    srcs = ["list_test.cc"],
    deps = [
        "//:gtest",
        "//:sdk_headers",
    ],
)
