package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "jenkins_spooky",
    srcs = [
        "spooky.cpp",
        "spooky.h",
    ],
    hdrs = [
        "spooky.h",
    ],
    deps = [
    ]
)
