package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "base_includes",
    srcs = [],
    hdrs = glob(["*.hpp", "*.h"]),
    deps = ["@sdk//:sdk_headers", "//nic:boost"]
)
