#ifndef __CAPRI_BARCO_H__
#define __CAPRI_BARCO_H__

#define CAPRI_BARCO_MD_HENS_REG_BASE                    (0x6580000)

#define CAPRI_BARCO_MD_HENS_REG_GCM0_PRODUCER_IDX       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x20c)
#define CAPRI_BARCO_MD_HENS_REG_GCM0_CONSUMER_IDX       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x280)

#define CAPRI_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM0        (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2000)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM1        (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2200)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_PSNL_STR           (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2400)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ENTROPY_INST       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2440)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ENTROPY_RESEED     (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2480)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ISR                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2500)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_MSK                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2504)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ICR                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2508)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_VER                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x250c)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_GCT                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2510)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RSVR0              (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2514)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_GS                 (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2518)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RSVR1              (CAPRI_BARCO_MD_HENS_REG_BASE + 0x250c)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RNG                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2520)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_DRNGE              (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2524)

#define CAPRI_BARCO_MP_MPNS_REG_BASE                    (0x6560000) // CAP_ADDR_BASE_MP_MPNS_OFFSET

#define CAPRI_BARCO_MP_MPNS_REG_MPP1_PRODUCER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x10c)
#define CAPRI_BARCO_MP_MPNS_REG_MPP1_CONSUMER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x180)

#define CAPRI_BARCO_MP_MPNS_REG_MPP2_PRODUCER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x20c)
#define CAPRI_BARCO_MP_MPNS_REG_MPP2_CONSUMER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x280)

#define CAPRI_BARCO_MP_MPNS_REG_MPP3_PRODUCER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x30c)
#define CAPRI_BARCO_MP_MPNS_REG_MPP3_CONSUMER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x380)

#define CAPRI_BARCO_COMMAND_HMAC_SHA256_GENERATE        0x23200000
#define CAPRI_BARCO_COMMAND_HMAC_SHA256_VERIFY          0x23300000
#define CAPRI_BARCO_COMMAND_HMAC_SHA384_GENERATE        0x24200000
#define CAPRI_BARCO_COMMAND_HMAC_SHA384_VERIFY          0x24300000
#define CAPRI_BARCO_COMMAND_HMAC_SHA512_GENERATE        0x25200000
#define CAPRI_BARCO_COMMAND_HMAC_SHA512_VERIFY          0x25300000

#define CAPRI_BARCO_COMMAND_AES_CBC_ENCRYPT             0x01000000
#define CAPRI_BARCO_COMMAND_AES_CBC_DECRYPT             0x01100000

#endif  /* __CAPRI_BARCO_H__ */
