#ifndef __CAPRI_BARCO_H__
#define __CAPRI_BARCO_H__

#define CAPRI_BARCO_MD_HENS_REG_BASE                    (0x6580000)

#define CAPRI_BARCO_MD_HENS_REG_GCM0_PRODUCER_IDX       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x20c)
#define CAPRI_BARCO_MD_HENS_REG_GCM0_CONSUMER_IDX       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x280)

#define CAPRI_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM0        (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2000)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RANDOM_NUM1        (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2200)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_PSNL_STR           (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2400)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ENTROPY_INST       (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2440)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ENTROPY_RESEED     (CAPRI_BARCO_MD_HENS_REG_BASE + 0x2480)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ISR                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3000)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_MSK                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3004)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_ICR                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3008)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_VER                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x300c)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_GCT                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3010)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_GS                 (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3014)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_RNG                (CAPRI_BARCO_MD_HENS_REG_BASE + 0x3018)
#define CAPRI_BARCO_MD_HENS_REG_DRBG_DRNGE              (CAPRI_BARCO_MD_HENS_REG_BASE + 0x301c)

#define CAPRI_BARCO_MP_MPNS_REG_BASE                    (0x6560000) // CAP_ADDR_BASE_MP_MPNS_OFFSET

#define CAPRI_BARCO_MP_MPNS_REG_MPP1_PRODUCER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x10c)
#define CAPRI_BARCO_MP_MPNS_REG_MPP1_CONSUMER_IDX       (CAPRI_BARCO_MP_MPNS_REG_BASE + 0x180)

#endif  /* __CAPRI_BARCO_H__ */
