
// TODO: Not sure about these numbers. Real slacl implementation please double
// check
#define SLACL_SPORT_TABLE_SIZE          1024
#define SLACL_IPV4_TABLE_SIZE           16384
#define SLACL_PROTO_DPORT_TABLE_SIZE    16384
#define SLACL_P1_TABLE_SIZE             165000
#define SLACL_P2_TABLE_SIZE             262144


#define SLACL_SPORT_TABLE_OFFSET        0
#define SLACL_IPV4_TABLE_OFFSET         (SLACL_SPORT_TABLE_SIZE)
#define SLACL_PROTO_DPORT_TABLE_OFFSET  \
    (SLACL_IPV4_TABLE_OFFSET + SLACL_IPV4_TABLE_SIZE)
#define SLACL_P1_TABLE_OFFSET           \
    (SLACL_PROTO_DPORT_TABLE_OFFSET + SLACL_PROTO_DPORT_TABLE_SIZE)
#define SLACL_P2_TABLE_OFFSET           \
    (SLACL_P1_TABLE_OFFSET + SLACL_P1_TABLE_SIZE)
