package(default_visibility = ["//visibility:public"])

cc_library(
    name = "utils",
    srcs = [
    ] + glob(["*.cc"]),
    hdrs = [
    ] + glob(["*.hpp"]),
    deps = [
        "//nic:spdlog",
    ],
    include_prefix = "nic/upgrade_manager/utils",
)
