#include "../include/headers.p4"
#include "../include/apulu_defines.h"
#include "../include/apulu_headers.p4"
#include "../include/apulu_table_sizes.h"
#include "../include/apulu_sacl_defines.h"
#include "../include/lpm_defines.h"

#include "mapping.p4"
#include "tags.p4"
#include "sacl_lpm.p4"
#include "vnic_info_rxdma.p4"
#include "packet_queue.p4"

#include "common_rxdma_dummy_actions.p4"
#include "common_rxdma.p4"
#include "metadata.p4"
