package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "p4pd_mock",
    srcs = ["p4pd_mock.cc"],
    hdrs = [],
    deps = [
        "//nic/include:base_includes",
        "//nic/third-party/spdlog",
    ],
)
