
TOPDIR = ../../../..
SHAREDLIBRARY = libp4pd_mock.so

LCXXFLAGS = \
			-I../../../../include \
			-I../../../../third-party/spdlog/include

SOURCES = \
	p4pd_mock.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
