#
# Copyright (c) 2017, Pensando Systems Inc.
#

LIBRARY = libcfgspace.a libcfgspace.so
SOURCES = \
	cfgspace_getset.c \
	cfgspace_header.c \
	cfgspace_caps.c \
	cfgspace_extcaps.c \
	cfgspace_readwrite.c \
	$(NULL)

LCFLAGS += -I ../include

TOPDIR = ../../../..
include $(TOPDIR)/make/Makefile.inc
