
LIBDIRS = $(NULL)

PGMDIRS = \
	rxdma\
        txdma1\
        txdma2\
	$(NULL)

SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../../..

include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc
