
LIBDIRS = $(NULL)

PGMDIRS = \
	esp_ipv4_tunnel_host_to_network \
	esp_ipv4_tunnel_network_to_host \
	$(NULL)

SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..

include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc
