TOPDIR = ../../..
CUSTOM = all
CUSTOM_CLEAN = clean

include $(TOPDIR)/make/Makefile.inc



CXX = g++
CPPFLAGS += -I/usr/local/include -std=c++11 -g -DHAL_MRL_PORT
OBJ_DIR = ../../../obj
INC_DIRS = -I. -I./mrl -I.. -I../.. -I../../../include -I../../../third-party/spdlog/include
INC_DIRS += -I../../../capsim/lib/libmpuobj/include/
INC_DIRS += -I../../../capsim/lib/libcapisa/include/
INC_DIRS += -I../../../model_sim/include
INC_DIRS += -I../../../gen/iris/include/
LIB_DIR = ../../../model_sim/build
LDFLAGS = -L/usr/local/lib -L../../../model_sim/build -L../../../obj

LIBS = ../../../capsim/gen/lib/libmpuobj.a
LIBS += ../../../capsim/gen/lib/libcapisa.a
LIBS += ../../../capsim/gen/lib/libisa.a

SRCS := \
    capri_init.cc \
    capri_asic_rw.cc \
    capri_loader.cc \
    capri_tbl_rw.cc \
    capri_repl.cc \
	capri_hbm.cc \
    $(NULL)

OBJS := $(basename $(SRCS))
OBJS := $(OBJS:%=$(OBJ_DIR)/%.o)

all: $(OBJS)
	$(CXX) -shared -o $(OBJ_DIR)/libcapri.so $(OBJS) \
        -Wl,--whole-archive $(LIBS) -Wl,--no-whole-archive -L$(LIB_DIR) \
		-lmodelclient -lzmq $(LDFLAGS) -lcaprimrl

$(OBJ_DIR)/%.o : %.cc
	$(CXX) $(CPPFLAGS) $(INC_DIRS) -c -Wall -Werror -fpic -o $@ $<

clean:
	rm -rf $(OBJ_DIR)/*capri*.o $(OBJ_DIR)/libcapri.so
