#
# Copyright (c) 2017-2018, Pensando Systems Inc.
#

LIBRARY = libmnet.a libmnet.so
SOURCES = \
	mnet.c \
	$(NULL)

LCFLAGS += -I ../include

TOPDIR = ../../../..
include $(TOPDIR)/make/Makefile.inc
