package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "liblinuxionic_hdrs",
    hdrs = [
        "ionic_if.h",
    ],
    include_prefix = "platform/drivers/linux/eth/ionic",
)

