#include "../include/headers.p4"
#include "../include/artemis_defines.h"
#include "../include/artemis_headers.p4"
#include "../include/artemis_table_sizes.h"

#include "qstate.p4"
#include "route.p4"
#include "rfc.p4"
#include "dma.p4"
#include "iflow.p4"
#include "mapping.p4"
#include "remote_46_mapping.p4"
#include "vnic_info_txdma.p4"
#include "flow.p4"

#include "common_txdma_dummy_actions.p4"
#include "common_txdma.p4"
#include "metadata.p4"
