#include "../include/defines.h"
#include "../include/artemis_headers.p4"
#include "common_txdma_dummy_actions.p4"

#include "qstate.p4"
#include "route.p4"
#include "rfc.p4"
#include "dma.p4"
#include "common_txdma.p4"
#include "metadata.p4"
