

LIBDIRS = \
          trace \
          slab \
          twheel \
          fsm \
          shm \
          ht \
          pt \
          bitmap \
          indexer \
          thread \
          print \
          host_mem \
          $(NULL)
PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ..
include $(TOPDIR)/make/Makefile.inc
