
TOPDIR = ../../../..
BUILDOBJS = xx

LCXXFLAGS = \
			-I.. \
			-I../../../../include \
			-I../../../../hal/pd \
			-I../../../../gen/iris/include \
			-I../../../../third-party/spdlog/include

SOURCES = \
	met.cc \
	repl_list.cc \
	repl_table_entry.cc \
	repl_entry.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
