#!/bin/sh

npass=0
nfail=0
for tc in testcases/*.enc; do
    tb=`echo $tc | sed -e 's/\.enc$//'`
    ./pcietlp.gen -e $tc > $tb.out
    if ! cmp -s $tb.exp $tb.out; then
	printf "%-30s FAILED ***\n" $tc
	diff $tb.exp $tb.out
	nfail=`expr $nfail + 1`
    else
	printf "%-30s passed\n" $tc
	rm $tb.out
	npass=`expr $npass + 1`
    fi
done

echo Passed: $npass Failed: $nfail
if [ $nfail != 0 ]; then exit 1; fi
exit 0
