package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

# LIST
cc_library(
    name = "list",
    srcs = ["list.cc"],
    hdrs = ["list.hpp"],
    deps = [
        "//:sdk_headers",
    ],
)
