package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "plugins_includes",
    srcs = [],
    hdrs = [
            "plugins.hpp"
            ],
)
