---
version: 2.0
targets:
  build_x86-64:
    commands: [ "sh", "-c", "cd /sw/nic && make ARCH=x86_64" ]
    owners: ["email:neel@pensando.io"]
    area:
    sub-area:
    feature:
  build_aarch64:
    commands: [ "sh", "-c", "cd /usr/src/github.com/pensando/sw/nic && make ARCH=aarch64" ]
    owners: ["email:neel@pensando.io"]
    area:
    sub-area:
    feature:
  ##nicmgr_gtest: [ "sh", "-c", "make && cd /sw/nic && ./run.py --nicmgr_gtest" ]
  ##nicmgr_classic_gtest: [ "sh", "-c", "make && cd /sw/nic && ./run.py --nicmgr_gtest --classic" ]
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/platform"
rebase: true
#warmd:
#  target:
#    commands: [ "sh", "-c", "cd /sw && make e2e-turin && test/bin/e2e-turin  test --topo-file 2_naples_qemu_node.yaml" ]
#    owners: ["email:neel@pensando.io"]
#    area:
#    sub-area:
#    feature:
#  create:
#    image: build-38
#    count: 2
#    resources:
#      cpus: 8
#      memory: 16
#      pvt-networks:
#            - data
#            - control
#
#  provision:
#    username: vm
#    password: vm
