#
# Copyright (c) 2017, Pensando Systems Inc.
#

PROGRAM = prt_size_encode
SOURCES = prt_size_encode.c

LCFLAGS = \
	-I ../../../misc/include \
	$(NULL)

LIBRARIES = \
	-lmisc \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc
