package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libcfgspace_hdrs",
    hdrs = [
        "cfgspace.h",
    ],
    include_prefix = "platform/src/lib/cfgspace/include",
)

