package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpciehost_hdrs",
    hdrs = [
        "pciehbar.h",
        "pciehbar_impl.h",
        "pciehcfg.h",
        "pciehcfg_impl.h",
        "pciehdev.h",
        "pciehdev_impl.h",
        "pciehost.h",
    ],
    include_prefix = "platform/src/lib/pciehost/include",
)

