#
# Copyright (c) 2017-2018, Pensando Systems Inc.
#

SUBDIRS = \
	capmon \
	captrace \
	capview \
	cpmem \
	example \
	memtun \
	pciemgrd \
	pcieutil \
	regio \
	nicmgrd \
	nicmgr_gtest \
	cpldapp \
	$(NULL)

TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
