#
# Copyright (c) 2017, Pensando Systems Inc.
#

SUBDIRS = \
	capmon \
	captrace \
	capview \
	cpmem \
	example \
	pciemgrd \
	pcieutil \
	regio \
	$(NULL)

TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
