LIBDIRS = \
          esp_ipv4_tunnel_host_to_network \
          esp_ipv4_tunnel_network_to_host \
          $(NULL)

PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc
