package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "p4_oracle_includes",
    srcs = [],
    hdrs = ["defines.h",
            "table_sizes.h"],
)
