#define CPU_TO_P4PLUS_FLAGS_UPD_VLAN        0x0001
#define CPU_TO_P4PLUS_FLAGS_ADD_TX_QS_TRLR  0x0002

#define L2HDR_DOT1Q_OFFSET              12

#define CPUCB_FLAG_ADD_QS_PKT_TRLR      0x1
#define CPU_HASH_KEY_PREFIX             0x6D5A6D5A
#define CPU_HASH_KEY_SHIFT              32
