# {C} Copyright 2017 Pensando Systems Inc. All rights reserved

package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

# mock for table management libs' test cases
cc_library(
    name = "p4pd_mock",
    srcs = ["p4pd_mock.cc"],
    hdrs = [],
    deps = [
        "//:sdk_headers",
    ],
)
