#define SLACL_IP_TABLE_SIZE                                 82304
#define SLACL_PORT_TABLE_SIZE                               65536
#define SLACL_PROTO_TABLE_SIZE                              128
#define SLACL_P1_C0C2_TABLE_SIZE                            329024
#define SLACL_P1_C1C3_TABLE_SIZE                            329024
#define SLACL_P2_C6C4_TABLE_SIZE                            20608
#define SLACL_P3_TABLE_SIZE                                 2097152
#define SLACL_STATS_TABLE_SIZE                              1048576

#define SLACL_IP_TABLE_OFFSET \
    (SLACL_IP_TABLE_SIZE)
#define SLACL_SPORT_TABLE_OFFSET \
     (SLACL_IP_TABLE_OFFSET + SLACL_IP_TABLE_SIZE)
#define SLACL_DPORT_TABLE_OFFSET \
    (SLACL_SPORT_TABLE_OFFSET + SLACL_PORT_TABLE_SIZE)
#define SLACL_PROTO_TABLE_OFFSET \
    (SLACL_DPORT_TABLE_OFFSET + SLACL_PORT_TABLE_SIZE)
#define SLACL_P1_C0C2_TABLE_OFFSET \
    (SLACL_PROTO_TABLE_OFFSET + SLACL_PROTO_TABLE_SIZE)
#define SLACL_P1_C1C3_TABLE_OFFSET \
    (SLACL_P1_C0C2_TABLE_OFFSET + SLACL_P1_C0C2_TABLE_SIZE)
#define SLACL_P2_C6C4_TABLE_OFFSET \
    (SLACL_P1_C1C3_TABLE_OFFSET + SLACL_P1_C1C3_TABLE_SIZE)
#define SLACL_P3_TABLE_OFFSET \
    (SLACL_P2_C6C4_TABLE_OFFSET + SLACL_P2_C6C4_TABLE_SIZE)
