
TOPDIR = ../../..
SHAREDLIBRARY = libpdcommon.so

LCXXFLAGS = \
			-I../../../include \
			-I../../../third-party/spdlog/include

SOURCES = \
	hal_pd.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
