
TOPDIR = ../../..
SHAREDLIBRARY = libpdcommon.so

LCXXFLAGS = \
			-I../ \
			-I../../../include \
			-I../../../gen/common_rxdma_actions/include \
			-I../../../gen/iris/include \
			-I../../../third-party/spdlog/include

SOURCES = \
	hal_pd.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
