package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libnicmgr_hdrs",
    hdrs = [
        "dev.hpp",
        "eth_dev.hpp",
        "accel_dev.hpp",
        "hal_client.hpp",
    ],
    include_prefix = "platform/src/lib/nicmgr/include",
)

