package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libnicmgr_hdrs",
    hdrs = glob(["*.hpp"]),
    include_prefix = "platform/src/lib/nicmgr/include",
)

