export enum Eventtypes {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  GOOGLE_CHART_LOADED,
  COMPONENT_INIT,
  COMPONENT_DESTROY,
  AJAX_START,
  AJAX_END,
  GOOGLE_CHART_LOADING,
  SIDENAV_INVOKATION_REQUEST,
  SEARCH_RESULT_LOAD_REQUEST,
  TOOLBAR_DATA_CHANGE,
  PIN_REQUEST,
  UNPIN_REQUEST,
  IDLE_CHANGE,
  SEARCH_SET_SEARCHSTRING_REQUEST,
  SEARCH_OPEN_GUIDEDSERCH_REQUEST
  /*
  PAGE_DIRTY,

  */

}
