export enum Eventtypes {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  GOOGLE_CHART_LOADED,
  COMPONENT_INIT,
  COMPONENT_DESTROY,
  AJAX_START,
  AJAX_END,
  GOOGLE_CHART_LOADING,
  SIDENAV_INVOKATION_REQUEST,
  SIDENAV_NAVIGATION_END,
  SEARCH_RESULT_LOAD_REQUEST,
  TOOLBAR_DATA_CHANGE,
  PIN_REQUEST,
  UNPIN_REQUEST,
  IDLE_CHANGE,
  SEARCH_SET_SEARCHSTRING_REQUEST,
  SEARCH_OPEN_GUIDEDSERCH_REQUEST,
  FETCH_USER_OBJ,
  FETCH_USER_PREFERENCES,
  FETCH_USER_PERMISSIONS,
  NEW_USER_PERMISSIONS, // Triggered when ui permissions changes.
  NEW_FEATURE_PERMISSIONS, // Triggered when ui feature permissions changes. Mainly for testing env
  HELP_CONTENT_CHANGE,
  HELP_OVERLAY_OPEN,
  HELP_OVERLAY_CLOSE,
  BACKGROUND_FILEUPLOAD_PROGRESS,
  BACKGROUND_FILEUPLOAD_SUCCESS,
  BACKGROUND_FILEUPLOAD_FAILURE,
  BACKGROUND_FILEUPLOAD_CANCEL,
  /*
  PAGE_DIRTY,

  */

}
