export enum Eventtypes {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    NOT_YET_LOGIN,
    LOGOUT,
    GOOGLE_CHART_LOADED,
    COMPONENT_INIT,
    COMPONENT_DESTROY,
    AJAX_START,
    AJAX_END,
    GOOGLE_CHART_LOADING,
    SIDENAV_INVOKATION_REQUEST,
    TOOLBAR_DATA_CHANGE,
    PIN_REQUEST,
    UNPIN_REQUEST,
    IDLE_CHANGE
    /*
    PAGE_DIRTY,

    */

}
