LIBDIRS = \
          common \
          resp_tx \
          resp_rx \
          req_tx \
          req_rx \
          cq_tx \
          cq_rx \
          $(NULL)
PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..

include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc

