
# Copyright (c) 2017, Pensando Systems Inc.

TOPDIR = ../../..

LBUILD_ARCHES = aarch64

PROGRAM = regio

SOURCES = \
	main.c \
	$(NULL)

LCFLAGS = -I $(TOPDIR)/src/lib/pal/include
LIBRARIES = -lpal

include $(TOPDIR)/make/Makefile.inc
