---
version: 2.0
targets:
  infra:
    commands: [ "bash", "-c", "cd /sw/dol && ./sanity.sh" ]
    owners: ["email:vikasd@pensando.io"]
    area:
    sub-area:
    feature:
  regr:
    commands: [ "bash", "-c", "cd /sw/dol && ./regression.sh" ]
    owners: ["email:vikasd@pensando.io"]
    area:
    sub-area:
    feature:
cache:
  name: "sw"
  mount_dir: "/root/.cache"
image:
  bind_dir: "/sw"
  work_dir: "/sw/dol"
rebase: true
