package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "modelsim_includes",
    srcs = [],
    hdrs = [
            "buf_hdr.h",
            "c2scapy.h",
            "cap_blk_env_base.h",
            "cap_env_base.h",
            "cap_model_base.h",
            "cpu_bus_base.h",
            "cpu_bus_stub.h",
            "cpu.h",
            "HBM.h",
            "HOST_MEM.h",
            "lib_model_client.h",
            "LogMsg.h",
            "pen_mem_base.h",
            "pen_mem.h",
            "pknobs.h",
            "scapy_pkt_gen.h",
            # symlinked from /home/asic/.... Please FIX
            "sknobs.h"
            ],
)
