#!/bin/bash

#Parse Command line options first.
getopt --test > /dev/null
if [[ $? -ne 4 ]]; then
    echo "I?m sorry, `getopt --test` failed in this environment."
    exit 1
fi
LONGOPTIONS="img:,memory:,skip-kvm-accel"

PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
if [[ $? -ne 0 ]]; then
    # e.g. $? == 1
    #  then getopt has complained about wrong arguments to stdout
    exit 2
fi

eval set -- "$PARSED"
while true; do
    case "$1" in
         --skip-kvm-accel)
            NO_KVM_ACCEL=1
            shift
            ;;
        --img)
            DRIVE_IMG=$2
            shift 2
            ;;
        --memory)
            MEMORY=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error $1"
            exit 3
            ;;
    esac
done

if [  -z "$DRIVE_IMG" ];then
    echo "Image not provided, use --img"
    exit 1
fi

if [  -z "$MEMORY" ];then
    QEMU_MEMORY_MB=256
else    
    QEMU_MEMORY_MB=$MEMORY
fi
if [  -z "$NO_KVM_ACCEL" ];then
    QEMU_MACHINE="q35,accel=kvm"
else    
    QEMU_MACHINE="q35"
fi

: ${QEMU_SERIAL_PORT:=1034}
: ${QEMU_MONITOR_PORT:=1035}
: ${QEMU_SSH_PORT:=1037}

SCRIPT_DIR=`dirname $0`
SCRIPT_PATH=`cd $SCRIPT_DIR; echo $PWD`
TOP_PATH=`cd $SCRIPT_DIR/../../..; echo $PWD`
GEN=$TOP_PATH/gen/x86_64
GENBIN=$GEN/bin
GENLIB=$GEN/lib

# New LD_LIBRARY_PATH
N=$GENLIB
# append original LD_LIBRARY_PATH, if any
[ -n "$LD_LIBRARY_PATH" ] && N=${N}:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${N}

QEMU_VERSION=2.9.0
QEMU_DIR=$SCRIPT_PATH/qemu-$QEMU_VERSION
$GDB $QEMU_DIR/x86_64-softmmu/qemu-system-x86_64 \
    -machine $QEMU_MACHINE -smp cpus=4,sockets=2,cores=2 -nographic -m $QEMU_MEMORY_MB \
    -serial telnet::$QEMU_SERIAL_PORT,server,nowait \
    -monitor telnet::$QEMU_MONITOR_PORT,server,nowait \
    -netdev user,id=net0,hostfwd=tcp::$QEMU_SSH_PORT-:22 \
    -device e1000,netdev=net0 \
    -device ioh3420,id=pcie_bus1 \
    -device simbridge,bus=pcie_bus1 \
    -drive file=$DRIVE_IMG,if=virtio $QEMU_EXTRA
