#
# Copyright (c) 2018, Pensando Systems Inc.
#

PROGRAM = palutils
SOURCES = pal_utils.c

LCFLAGS = \
	-I ../../../pal/include \
	$(NULL)

LIBRARIES = \
	-lpal \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc

