
TOPDIR = ../../../..
# SHAREDLIBRARY = libpddirectmap.so
BUILDOBJS = xx

LCXXFLAGS = \
			-I.. \
			-I$(TOPDIR)/include \
			-I$(TOPDIR)/gen/iris/include \
			-I$(TOPDIR)/third-party/spdlog/include

SOURCES = \
	hbm_hash.cc \
	hbm_hash_entry.cc \
	hbm_hash_hint_group.cc \
	hbm_hash_spine_entry.cc \
	hbm_hash_table_entry.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc

