
sysmgr.pb.go: sysmgr.proto
	protoc --delphigo_out=Mdelphi.proto=github.com/pensando/sw/nic/delphi/proto/delphi:. \
        	./sysmgr.proto -I . -I /usr/src/github.com/pensando/sw -I /usr/src/github.com/pensando/sw/nic/sysmgr -I /usr/src/github.com/pensando/sw/nic/delphi/proto/delphi
