
sysmgr.pb.go: sysmgr.proto
	protoc --delphigo_out=Mnic/delphi/proto/delphi/delphi.proto=github.com/pensando/sw/nic/delphi/proto/delphi:. \
		./sysmgr.proto -I . -I /usr/src/github.com/pensando/sw -I /usr/src/github.com/pensando/sw/nic/sysmgr
