package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libsimlib_hdrs",
    hdrs = [
        "simclient.h",
        "simmsg.h",
        "simserver.h",
    ],
    include_prefix = "platform/src/sim/libsimlib/include",
)

