//
// {C} Copyright 2020 Pensando Systems Inc. All rights reserved
//
//----------------------------------------------------------------------------
///
/// \file
/// schema definitions for metrics and other helpers
///
//----------------------------------------------------------------------------

#include "nic/sdk/include/sdk/base.hpp"
#include "nic/sdk/include/sdk/types.hpp"
#include "nic/apollo/api/internal/metrics.hpp"

namespace api {

sdk::metrics::schema_t port_schema = {
    .name = "MacMetrics",
    .type = sdk::metrics::HBM,
    .counters = {
        "Frames Rx ok",
        "Frames Rx all",
        "Frames Rx bad fcs",
        "Frames Rx bad all",
        "Octets Rx ok",
        "Octets Rx all",
        "Frames Rx unicast",
        "Frames Rx multicast",
        "Frames Rx broadcast",
        "Frames Rx pause",
        "Frames Rx bad length",
        "Frames Rx undersized",
        "Frames Rx oversized",
        "Frames Rx fragments",
        "Frames Rx jabber",
        "Frames Rx priority pause",
        "Frames Rx stomped crc",
        "Frames Rx too long",
        "Frames Rx vlan good",
        "Frames Rx drop",
        "Frames Rx less than 64B",
        "Frames Rx 64B",
        "Frames Rx 65B-127B",
        "Frames Rx 128B-255B",
        "Frames Rx 256B-511B",
        "Frames Rx 512B-1023B",
        "Frames Rx 1024B-1518B",
        "Frames Rx 1519B-2047B",
        "Frames Rx 2048B-4095B",
        "Frames Rx 4096B-8191B",
        "Frames Rx 8192B-9215B",
        "Frames Rx other",
        "Frames Tx ok",
        "Frames Tx all",
        "Frames Tx bad",
        "Octets Tx ok",
        "Octets Tx total",
        "Frames Tx unicast",
        "Frames Tx multicast",
        "Frames Tx broadcast",
        "Frames Tx pause",
        "Frames Tx priority pause",
        "Frames Tx vlan",
        "Frames Tx less than 64B",
        "Frames Tx 64B",
        "Frames Tx 65B-127B",
        "Frames Tx 128B-255B",
        "Frames Tx 256B-511B",
        "Frames Tx 512B-1023B",
        "Frames Tx 1024B-1518B",
        "Frames Tx 1519B-2047B",
        "Frames Tx 2048B-4095B",
        "Frames Tx 4096B-8191B",
        "Frames Tx 8192B-9215B",
        "Frames Tx other",
        "Frames Tx priority 0",
        "Frames Tx priority 1",
        "Frames Tx priority 2",
        "Frames Tx priority 3",
        "Frames Tx priority 4",
        "Frames Tx priority 5",
        "Frames Tx priority 6",
        "Frames Tx priority 7",
        "Frames Rx priority 0",
        "Frames Rx priority 1",
        "Frames Rx priority 2",
        "Frames Rx priority 3",
        "Frames Rx priority 4",
        "Frames Rx priority 5",
        "Frames Rx priority 6",
        "Frames Rx priority 7",
        "Tx priority pause 0 1us count",
        "Tx priority pause 1 1us count",
        "Tx priority pause 2 1us count",
        "Tx priority pause 3 1us count",
        "Tx priority pause 4 1us count",
        "Tx priority pause 5 1us count",
        "Tx priority pause 6 1us count",
        "Tx priority pause 7 1us count",
        "Rx priority pause 0 1us count",
        "Rx priority pause 1 1us count",
        "Rx priority pause 2 1us count",
        "Rx priority pause 3 1us count",
        "Rx priority pause 4 1us count",
        "Rx priority pause 5 1us count",
        "Rx priority pause 6 1us count",
        "Rx priority pause 7 1us count",
        "Rx pause 1us count",
        "Frames Tx truncated",
        NULL,
    }
};


sdk::metrics::schema_t mgmt_port_schema = {
    .name = "MgmtMacMetrics",
    .type = sdk::metrics::HBM,
    .counters = {
        "Frames Rx ok",
        "Frames Rx all",
        "Frames Rx bad fcs",
        "Frames Rx bad all",
        "Octets Rx ok",
        "Octets Rx all",
        "Frames Rx unicast",
        "Frames Rx multicast",
        "Frames Rx broadcast",
        "Frames Rx pause",
        "Frames Rx bad length",
        "Frames Rx undersized",
        "Frames Rx oversized",
        "Frames Rx fragments",
        "Frames Rx jabber",
        "Frames Rx 64B",
        "Frames Rx 65B-127B",
        "Frames Rx 128B-255B",
        "Frames Rx 256B-511B",
        "Frames Rx 512B-1023B",
        "Frames Rx 1024B-1518B",
        "Frames Rx > 1518B",
        "Frames Rx fifo full",
        "Frames Tx ok",
        "Frames Tx all",
        "Frames Tx bad",
        "Octets Tx ok",
        "Octets Tx total",
        "Frames Tx unicast",
        "Frames Tx multicast",
        "Frames Tx broadcast",
        "Frames Tx pause",
        NULL,
    }
};

sdk::metrics::schema_t hostif_schema = {
    .name = "LifMetrics",
    .type = sdk::metrics::HBM,
    .counters = {
        "Octets Rx unicast",
        "Frames Rx unicast",
        "Octets Rx multicast",
        "Frames Rx multicast",
        "Octets Rx broadcast",
        "Frames Rx broadcast",
        "_",
        "_",
        "Octets Rx unicast drop",
        "Frames Rx unicast drop",
        "Octets Rx multicast drop",
        "Frames Rx multicast drop",
        "Octets Rx broadcast drop",
        "Frames Rx broadcast drop",
        "Rx DMA error",
        "_",
        "Octets Tx unicast",
        "Frames Tx unicast",
        "Octets Tx multicast",
        "Frames Tx multicast",
        "Octets Tx broadcast",
        "Frames Tx broadcast",
        "_",
        "_",
        "Octets Tx unicast drop",
        "Frames Tx unicast drop",
        "Octets Tx multicast drop",
        "Frames Tx multicast drop",
        "Octets Tx broadcast drop",
        "Frames Tx broadcast drop",
        "Tx DMA error",
        "_",
        "Frames Rx queue disable drops",
        "Frames Rx queue empty drops",
        "Rx queue scheduling errors",
        "Rx descriptor fetch errors",
        "Rx descriptor data fetch errors",
        "_",
        "_",
        "_",
        "Frames Tx queue disabled drops",
        "Tx queue scheduling errors",
        "Tx descriptor fetch errors",
        "Tx descriptor data fetch errors",
        "_",
        "_",
        "_",
        "_",
        "Octets Tx RDMA unicast",
        "Frames Tx RDMA unicast",
        "Octets Tx RDMA multicast",
        "Frames Tx RDMA multicast",
        "Frames Tx RDMA CNP",
        "_",
        "_",
        "_",
        "Octets Rx RDMA unicast",
        "Frames Rx RDMA unicast",
        "Octets Rx RDMA multicast",
        "Frames Rx RDMA multicast",
        "Frames Rx RDMA CNP",
        "Frames Rx RDMA ECN",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "_",
        "Frames Rx RDMA request sequence errors",
        "Rx RDMA request RNR retry errors",
        "Rx RDMA request remote access errors",
        "Rx RDMA request remote invalid request errors",
        "Rx RDMA request remote operation errors",
        "Rx RDMA request implied NACK sequence errors",
        "Rx RDMA request CQE errors",
        "Rx RDMA request CQE flush errors",
        "Rx RDMA request duplicate responses",
        "Frames Rx RDMA request invalid",
        "Tx RDMA request local access errors",
        "Tx RDMA request local operation errors",
        "Tx RDMA request memory management errors",
        "_",
        "_",
        "_",
        "Rx RDMA response duplicate request errors",
        "Rx RDMA response out of buffer errors",
        "Rx RDMA response out of sequence errors",
        "Rx RDMA response CQE errors",
        "Rx RDMA response CQE flush errors",
        "Rx RDMA response local length errors",
        "Rx RDMA response invalid request errors",
        "Rx RDMA response local QP operation errors",
        "Rx RDMA response out of atomic resources errors",
        "Tx RDMA response packet sequence errors",
        "Tx RDMA response remote invalid request errors",
        "Tx RDMA response remote access errors",
        "Tx RDMA response remote operation errors",
        "Tx RDMA response RNR retry errors",
        "_",
        "_",
        NULL,
    }
};

}    // namespace api
