#!/bin/bash

# usage:
#
# rdmagen
#
# Copies and transforms generic source from common/ to the linux and freebsd
# trees using coan (https://sourceforge.net/projects/coan2/)
#

cd "$(readlink -f "$(dirname "$0")/../..")"

COAN="coan source -gw --no-transients"
GENBSD="platform/tools/gen-bsd.coan"
GENLINUX="platform/tools/gen-linux.coan"

COMMON_DRV="platform/drivers/common/rdma/drv"
LINUX_DRV="platform/drivers/linux/rdma/drv/ionic"
FBSD_DRV="platform/drivers/freebsd/usr/src/sys/dev/ionic/ionic_rdma"

DRV_FILES=(
    "ionic_ibdev.c"
    "ionic_ibdev.h"
    "ionic_admin.c"
    "ionic_controlpath.c"
    "ionic_datapath.c"
    "ionic_dcqcn.c"
    "ionic_fw.h"
    "ionic_kcompat.c"
    "ionic_kcompat.h"
    "ionic_pgtbl.c"
    "ionic_queue.c"
    "ionic_queue.h"
    "ionic_res.c"
    "ionic_res.h"
    "ionic_stats.c"
)
LINUX_DRV_FILES=(
    "ionic_sysfs.c"
    "ionic_sysfs.h"
    "ionic_kcompat_ofa.h"
    "${DRV_FILES[@]}"
)
FBSD_DRV_FILES=(
    "ionic_sysctl.c"
    "ionic_sysctl.h"
    "${DRV_FILES[@]}"
)

for FNAME in "${LINUX_DRV_FILES[@]}"; do
    $COAN -f $GENLINUX "${COMMON_DRV}/${FNAME}" > "${LINUX_DRV}/${FNAME}"
done

for FNAME in "${FBSD_DRV_FILES[@]}"; do
    $COAN -f $GENBSD "${COMMON_DRV}/${FNAME}" > "${FBSD_DRV}/${FNAME}"
done

COMMON_LIB="platform/drivers/common/rdma/lib"
LINUX_LIB="platform/drivers/linux/rdma/lib/ionic"
FBSD_LIB="platform/drivers/freebsd/usr/src/contrib/ofed/libionic"

LIB_FILES=(
    "ionic-abi.h"
    "ionic.c"
    "ionic_dbg.h"
    "ionic_fw.h"
    "ionic.h"
    "ionic_memory.c"
    "ionic_memory.h"
    "ionic_queue.c"
    "ionic_queue.h"
    "ionic_stats.h"
    "ionic_table.h"
    "ionic_verbs.c"
)

for FNAME in "${LIB_FILES[@]}"; do
    $COAN -f $GENLINUX "${COMMON_LIB}/${FNAME}" > "${LINUX_LIB}/${FNAME}"
    $COAN -f $GENBSD "${COMMON_LIB}/${FNAME}" > "${FBSD_LIB}/${FNAME}"
done
