
messenger.pb.go:
	protoc --go_out=Mdelphi.proto=github.com/pensando/sw/nic/delphi/proto/delphi:. \
		./messenger.proto -I ${GOPATH}/src/github.com/pensando/sw -I . \
		-I ${GOPATH}/src/github.com/pensando/sw/nic/delphi/proto/delphi

gen-clean:
