include ../../../build.mk

LDFLAGS = -L../../../model_sim/build -L../../../obj
LD_PATH = ../../../obj
CPPFLAGS += -DHAL_GTEST=1 -DHAL_MRL_PORT=1 -lcaprimrl
SRC_DIR = .
CAPRI_SRC_DIR = ../capri
IRIS_P4PD_SRC_DIR = ../iris/p4pd/
OBJ_DIR = ../../../obj
GEN_DIR = ../../../gen
GEN_TEST_RESULTS_DIR = ../../../gen/test_results
GTEST_ROOT = ../../../third-party/googletest-release-1.8.0/googletest
INCLUDE_DIRS = -I ../../../include -I.. -I../.. \
			   -I ../../../gen \
			   -I ../../../hal \
			   -I ../../../hal/pd \
			   -I ../capri \
			   -I ../capri/mrl \
               -I ../../../capsim/lib/libcapisa/include/ \
               -I ../../../capsim/lib/libmpuobj/include/ \
               -I ../../../model_sim/include/ \
			   -I ../../../gen/iris/include/ \
               -I $(SRC_DIR)/hash \
               -I $(SRC_DIR)/tcam \
         	-I $(SRC_DIR)/../../../third-party/spdlog/include \
			   -I $(GTEST_ROOT)/include \

LIBS = ../../../capsim/gen/lib/libmpuobj.a
LIBS += ../../../capsim/gen/lib/libcapisa.a
LIBS += ../../../capsim/gen/lib/libisa.a

CPP_SRC_FILES :=    $(SRC_DIR)/directmap/directmap.cc \
					$(SRC_DIR)/tcam/tcam.cc \
					$(SRC_DIR)/tcam/tcam_entry.cc \
					$(SRC_DIR)/hash/hash.cc \
					$(SRC_DIR)/hash/hash_entry.cc \
					$(SRC_DIR)/flow/flow.cc \
					$(SRC_DIR)/flow/flow_entry.cc \
					$(SRC_DIR)/flow/flow_hint_group.cc \
					$(SRC_DIR)/flow/flow_spine_entry.cc \
					$(SRC_DIR)/flow/flow_table_entry.cc \
					$(SRC_DIR)/met/met.cc \
					$(SRC_DIR)/met/repl_list.cc \
					$(SRC_DIR)/met/repl_table_entry.cc \
					$(SRC_DIR)/met/repl_entry.cc \
                    $(CAPRI_SRC_DIR)/capri_tbl_rw.cc \
                    $(IRIS_P4PD_SRC_DIR)/p4pd_api.cc \
                    $(CAPRI_SRC_DIR)/capri_loader.cc

C_SRC_FILES := $(SRC_DIR)/../../../gen/iris/src/p4pd.c

CPP_OBJ_FILES := $(patsubst %.cc, %.o, $(CPP_SRC_FILES))
C_OBJ_FILES := $(patsubst %.c, %.o, $(C_SRC_FILES))

$(CPP_OBJ_FILES): %.o: %.cc | $(OBJ_DIR)
	@echo Compiling $@
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -fpic -c $< -o $(OBJ_DIR)/$(shell basename $@)
	$(CXX) -include p4pd_stub.hpp $(INCLUDE_DIRS) $(CPPFLAGS) -fpic -c $< -o $(OBJ_DIR)/stub_$(shell basename $@)

$(C_OBJ_FILES): %.o: %.c | $(OBJ_DIR)
	@echo Compiling $@
	$(CC) $(INCLUDE_DIRS) $(CFLAGS) -fpic -c $< -o $(OBJ_DIR)/$(shell basename $@)

all: $(CPP_OBJ_FILES) $(C_OBJ_FILES)
	$(CXX) -shared -o $(OBJ_DIR)/libpdutils.so $(OBJ_DIR)/directmap.o $(OBJ_DIR)/tcam.o $(OBJ_DIR)/tcam_entry.o $(OBJ_DIR)/hash.o $(OBJ_DIR)/hash_entry.o $(OBJ_DIR)/flow.o $(OBJ_DIR)/flow_entry.o $(OBJ_DIR)/flow_hint_group.o $(OBJ_DIR)/flow_spine_entry.o $(OBJ_DIR)/flow_table_entry.o $(OBJ_DIR)/met.o $(OBJ_DIR)/repl_list.o $(OBJ_DIR)/repl_table_entry.o $(OBJ_DIR)/repl_entry.o $(OBJ_DIR)/capri_tbl_rw.o $(OBJ_DIR)/p4pd_api.o $(OBJ_DIR)/capri_loader.o
	$(CXX) -shared -o $(OBJ_DIR)/libpdutils_stub.so $(OBJ_DIR)/stub_directmap.o $(OBJ_DIR)/stub_tcam.o $(OBJ_DIR)/stub_tcam_entry.o $(OBJ_DIR)/stub_hash.o $(OBJ_DIR)/stub_hash_entry.o $(OBJ_DIR)/stub_flow.o $(OBJ_DIR)/stub_flow_entry.o $(OBJ_DIR)/stub_flow_hint_group.o $(OBJ_DIR)/stub_flow_spine_entry.o $(OBJ_DIR)/stub_flow_table_entry.o $(OBJ_DIR)/stub_met.o $(OBJ_DIR)/stub_repl_list.o $(OBJ_DIR)/stub_repl_table_entry.o $(OBJ_DIR)/stub_repl_entry.o $(OBJ_DIR)/stub_capri_tbl_rw.o $(OBJ_DIR)/stub_p4pd_api.o $(OBJ_DIR)/stub_capri_loader.o
	# -----------------       GTests      -------------------
	# $(CXX) -shared -o $(OBJ_DIR)/mock.so $(SRC_DIR)/directmap/mock.cc
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/directmap/directmap_test.cc $(GTEST_ROOT)/make/gtest.a $(LIBS) $(OBJ_DIR)/indexer.o $(OBJ_DIR)/p4pd.o -lpthread $(LDFLAGS) -lmodelclient -lzmq -lthread -lcapri -ltrace -lpdutils_stub -o $(OBJ_DIR)/directmap_test
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/tcam/tcam_test.cc $(GTEST_ROOT)/make/gtest.a $(LIBS) $(OBJ_DIR)/indexer.o $(OBJ_DIR)/p4pd.o -lpthread $(LDFLAGS) -lmodelclient -lzmq -lthread -lcapri -ltrace -lpdutils_stub -o $(OBJ_DIR)/tcam_test
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/hash/hash_test.cc $(GTEST_ROOT)/make/gtest.a $(LIBS) $(OBJ_DIR)/indexer.o $(OBJ_DIR)/p4pd.o -lpthread $(LDFLAGS) -lmodelclient -lzmq -lthread -lcapri -ltrace -lpdutils_stub -o $(OBJ_DIR)/hash_test
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/flow/flow_test.cc $(GTEST_ROOT)/make/gtest.a $(LIBS) $(OBJ_DIR)/indexer.o $(OBJ_DIR)/p4pd.o -lpthread $(LDFLAGS) -lmodelclient -lzmq -lthread -lcapri -ltrace -lpdutils_stub -o $(OBJ_DIR)/flow_test
	$(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/met/met_test.cc $(GTEST_ROOT)/make/gtest.a $(LIBS) $(OBJ_DIR)/indexer.o $(OBJ_DIR)/p4pd.o -lpthread $(LDFLAGS) -lmodelclient -lzmq -lthread -lcapri -ltrace -lpdutils_stub -o $(OBJ_DIR)/met_test

	# $(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/directmap/directmap_test.cc $(GTEST_ROOT)/make/gtest.a $(OBJ_DIR)/indexer.o $(OBJ_DIR)/directmap.o $(OBJ_DIR)/p4pd.o $(OBJ_DIR)/capri_tbl_rw.o $(OBJ_DIR)/p4pd_api.o $(OBJ_DIR)/capri_loader.o $(LIBS) -lpthread $(LDFLAGS) -lmodelclient -lzmq -ltrace -o $(OBJ_DIR)/directmap_test
	# $(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/tcam/tcam_test.cc $(GTEST_ROOT)/make/gtest.a $(OBJ_DIR)/indexer.o $(OBJ_DIR)/tcam.o $(OBJ_DIR)/tcam_entry.o $(OBJ_DIR)/p4pd.o $(OBJ_DIR)/capri_tbl_rw.o $(OBJ_DIR)/p4pd_api.o $(OBJ_DIR)/capri_loader.o $(LIBS) -lpthread $(LDFLAGS) -lmodelclient -lzmq -ltrace -o $(OBJ_DIR)/tcam_test
	# $(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/hash/hash_test.cc $(GTEST_ROOT)/make/gtest.a $(OBJ_DIR)/indexer.o $(OBJ_DIR)/hash.o $(OBJ_DIR)/hash_entry.o $(OBJ_DIR)/tcam.o $(OBJ_DIR)/tcam_entry.o $(CRC32_ROOT)/crc32.o $(OBJ_DIR)/p4pd.o $(OBJ_DIR)/capri_tbl_rw.o $(OBJ_DIR)/p4pd_api.o $(OBJ_DIR)/capri_loader.o $(LIBS) -lpthread $(LDFLAGS) -lmodelclient -lzmq -ltrace -o $(OBJ_DIR)/hash_test
	# $(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/flow/flow_test.cc $(GTEST_ROOT)/make/gtest.a $(OBJ_DIR)/indexer.o  $(OBJ_DIR)/flow.o  $(OBJ_DIR)/flow_entry.o  $(OBJ_DIR)/flow_hint_group.o  $(OBJ_DIR)/flow_spine_entry.o  $(OBJ_DIR)/flow_table_entry.o $(CRC32_ROOT)/crc32.o $(OBJ_DIR)/p4pd.o $(OBJ_DIR)/capri_tbl_rw.o $(OBJ_DIR)/p4pd_api.o $(OBJ_DIR)/capri_loader.o $(LIBS) -lpthread $(LDFLAGS) -lmodelclient -lzmq -ltrace -o $(OBJ_DIR)/flow_test
	# $(CXX) $(INCLUDE_DIRS) $(CPPFLAGS) -Wno-sign-compare $(SRC_DIR)/met/met_test.cc $(GTEST_ROOT)/make/gtest.a $(OBJ_DIR)/indexer.o $(OBJ_DIR)/met.o $(OBJ_DIR)/repl_list.o $(OBJ_DIR)/repl_table_entry.o $(OBJ_DIR)/repl_entry.o -lpthread $(LDFLAGS) -ltrace -o $(OBJ_DIR)/met_test

test:
	LD_LIBRARY_PATH=$(LD_PATH) $(OBJ_DIR)/directmap_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/directmap_test.xml"
	LD_LIBRARY_PATH=$(LD_PATH) $(OBJ_DIR)/tcam_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/tcam_test.xml"
	LD_LIBRARY_PATH=$(LD_PATH) $(OBJ_DIR)/hash_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/hash_test.xml"
	LD_LIBRARY_PATH=$(LD_PATH) $(OBJ_DIR)/flow_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/flow_test.xml"
	LD_LIBRARY_PATH=$(LD_PATH) $(OBJ_DIR)/met_test --gtest_output="xml:$(GEN_TEST_RESULTS_DIR)/met_test.xml"

clean:
	rm -rf $(OBJ_DIR)/*_test
	rm -rf $(GEN_TEST_RESULTS_DIR)/*.xml
