
TOPDIR = ../../..
SHAREDLIBRARY = libpdutils.so

OBJDIR = $(TOPDIR)/obj
SLOBJECTS = \
		  $(OBJDIR)/directmap.o \
		  $(OBJDIR)/tcam.o \
		  $(OBJDIR)/acl_tcam.o \
		  $(OBJDIR)/tcam_entry.o \
		  $(OBJDIR)/hash.o \
		  $(OBJDIR)/hash_entry.o \
		  $(OBJDIR)/flow.o \
		  $(OBJDIR)/flow_entry.o \
		  $(OBJDIR)/flow_hint_group.o \
		  $(OBJDIR)/flow_spine_entry.o \
		  $(OBJDIR)/flow_table_entry.o \
		  $(OBJDIR)/met.o \
		  $(OBJDIR)/repl_list.o \
		  $(OBJDIR)/repl_table_entry.o \
		  $(OBJDIR)/repl_entry.o \
		  $(OBJDIR)/capri_tbl_rw.o \
		  $(OBJDIR)/capri_loader.o \
		  $(OBJDIR)/p4pd_api.o \
		  $(OBJDIR)/p4pluspd_rxdma_api.o \
		  $(OBJDIR)/p4pluspd_txdma_api.o \
		  $(OBJDIR)/p4pd_global_api.o \
		  $(NULL)

include $(TOPDIR)/make/Makefile.inc
