LIBDIRS = \
          nw \
          common-p4+ \
          proxy \
          rdma \
          ipsec-p4+ \
          storage \
          cpu-p4plus \
          gc \
          raw-redir-p4+ \
          eth \
          ipfix \
          adminq \
          gft \
          $(NULL)

PGMDIRS = $(NULL)

SUBDIRS = $(LIBDIRS) $(PGMDIRS)

TOPDIR = ..


include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc
