#
# Copyright (c) 2018, Pensando Systems Inc.
#

PROGRAM = pali2c
SOURCES = \
	pali2c.c \
	$(NULL)

LCFLAGS = \
	-I ../../include \
	$(NULL)

LIBRARIES = \
	-lpal \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc
