#
# Copyright (c) 2017, Pensando Systems Inc.
#

PROGRAM = cpld 
SOURCES = cpld.c

LCFLAGS = \
	-I ../../src \
	$(NULL)

LIBRARIES = \
	-lpal \
	$(NULL)

TOPDIR = ../../../../..
include $(TOPDIR)/make/Makefile.inc
