#
# Copyright (c) 2017, Pensando Systems Inc.
#

PROGRAM = simd
SOURCES = simd.c

LIBRARIES = \
	-lsimdev \
	-lsimlib \
	-lpciehsvc \
	-lpciehw \
	-lpciehost \
	-lcfgspace \
	-lpal \
	-lmisc \
	$(NULL)

TOPDIR = ../../..
include $(TOPDIR)/make/Makefile.inc
