package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT license

cc_library(
    name = "trace",
    srcs = [
        "trace.cc",
        "trace.hpp",
    ],
    hdrs = ["trace.hpp"],
    deps = [
        "//nic/third-party/spdlog",
    ],
)
