package(default_visibility = ["//visibility:public"])

cc_library(
    name = "upgrade_common_includes",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.hpp"]),
    deps = [
        "//nic/upgrade_manager/upgrade:upgrade_gen",
    ],
)

