package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpciehsvc_hdrs",
    hdrs = [
        "pciehsvc.h",
    ],
    include_prefix = "platform/src/lib/pciehsvc/include",
)

