package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpciehw_hdrs",
    hdrs = [
        "pciehw.h",
        "pciehw_dev.h",
    ],
    include_prefix = "platform/src/lib/pciehw/include",
)

