package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "p4_common_includes",
    srcs = [],
    hdrs = ["common_defines.h", 
            ],
)
