bldproto:
	@protoc -I. -I${GOPATH}/src -I${GOPATH}/src/github.com/pensando/sw/vendor -I${GOPATH}/src/github.com/pensando/sw/vendor/github.com/gogo/protobuf/protobuf --pensando_out=plugins=grpc:. testmsg.proto
