# this is the base image for Venice components:
# ApiServer, ApiGw, VcHub, NPM, n4sagent
# includes libtool which is needed by keymgr for PKCS#11 backend
FROM alpine:3.6
RUN apk update
RUN apk add libtool

