#! /bin/bash
if [ -z "$NIC_DIR" ]; then
    export NIC_DIR=`dirname $PWD`
fi
export COVERAGE_CONFIG_PATH=$NIC_DIR/conf/
export COVERAGE_OUTPUT=$NIC_DIR/gen/coverage
export OBJ_DIR=$NIC_DIR/obj
$NIC_DIR/tools/gen_dol_cov_run.py
OUT=$?
if [ $OUT -ne 0 ];then
   echo "Dol coverage run generation failed!"
   exit 1
fi
$NIC_DIR/tools/gcov/run.py 2>&1 | tee $NIC_DIR/coverage.log
