#! /bin/bash
if [ -z "$NIC_DIR" ]; then
    export NIC_DIR=`dirname $PWD`
fi
export COVERAGE_CONFIG_PATH=$NIC_DIR/conf/
export COVERAGE_OUTPUT=$NIC_DIR/coverage

rm -rf $COVERAGE_OUTPUT

export MPU_COV_DUMP_FILE=$NIC_DIR/coverage/asm_cov.dump
export MPU_PC_COV_DUMP_DIR=$NIC_DIR/coverage/asm_out_all

#Remove mpu coverage dump file as its incremental.
rm -f $MPU_COV_DUMP_FILE
mkdir -p $MPU_PC_COV_DUMP_DIR

export CAPCOV=$NIC_DIR/asic/capri/model/capsim-gen/bin/capcov
export CAPRI_LOADER_CONF=$NIC_DIR/gen/capri_loader.conf
export GCOVR=$NIC_DIR/third-party/gcovr-3.3/scripts/gcovr

$NIC_DIR/tools/gen_dol_cov_run.py
OUT=$?
if [ $OUT -ne 0 ];then
   echo "Dol coverage run generation failed!"
   exit 1
fi
$NIC_DIR/tools/gcov/run.py 2>&1 | tee $NIC_DIR/coverage.log
