

LIBDIRS = \
	  nvme_vf_cmd \
	  pvm_vf_comp \
	  nvme_be_cmd \
	  nvme_be_comp \
	  r2n_cmd \
	  r2n_comp \
	  r2n_hbuf_post \
          $(NULL)
PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..
include $(TOPDIR)/make/Makefile.inc

