

LIBDIRS = \
	  storage_tx \
	  storage_seq \
	  storage_nvme \
          $(NULL)
PGMDIRS = $(NULL)
SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..

include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc

