package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "hal_pd_includes",
    srcs = [],
    hdrs = ["p4pd_api.hpp", "hal_pd_error.hpp", "asic_pd.hpp"],
)
