
TOPDIR = ../..
SHAREDLIBRARY = libprint.so

LCXXFLAGS = \
			-Wno-write-strings \
			-I../../include \
			-I../../third-party/spdlog/include

SOURCES = \
	print.cc \
	$(NULL)

include $(TOPDIR)/make/Makefile.inc
