#!/bin/sh

SCRIPT_DIR=`dirname $0`
SCRIPT_PATH=`cd $SCRIPT_DIR; echo $PWD`
NIC_DIR=$SCRIPT_PATH/../../../../nic
GEN=$SCRIPT_PATH/../../../gen/x86_64
GENBIN=$GEN/bin
GENLIB=$GEN/lib
MODEL_SERVER=$GENBIN/model_server

# New LD_LIBRARY_PATH
N=$NIC_DIR/model_sim/libs
N=${N}:$GENLIB
# append original LD_LIBRARY_PATH, if any
[ -n "$LD_LIBRARY_PATH" ] && N=${N}:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${N}

cd $NIC_DIR
echo $GDB $MODEL_SERVER \
    +PLOG_MAX_QUIT_COUNT=0 \
    +plog=info \
    +model_debug=$NIC_DIR/gen/iris/dbg_out/model_debug.json \
    $*
$GDB $MODEL_SERVER \
    +PLOG_MAX_QUIT_COUNT=0 \
    +plog=info \
    +model_debug=$NIC_DIR/gen/iris/dbg_out/model_debug.json \
    $*
