#
# Copyright (c) 2017, Pensando Systems Inc.
#

LIBRARY = libsimdev.a libsimdev.so
SOURCES = \
	simdev.c \
	simdev_msg_handler.c \
	devparams.c \
	generic_dev.c \
	eth_dev.c \
	accel_dev.c \
	virtio_dev.c \
	dev_utils.c \
	$(NULL)

TOPDIR = ../../../..
include $(TOPDIR)/make/Makefile.inc
