

LIBDIRS = $(NULL)

PGMDIRS =  \
      rx \
      tx \
	  virtio_tx \
	  virtio_rx \
      $(NULL)

SUBDIRS = $(LIBDIRS) $(PGMDIRS)
TOPDIR = ../..


include $(TOPDIR)/make/Makefile.inc
include $(TOPDIR)/make/Make.inc
