metrics  = [
  {
    name: 'Node',
    objectKind: 'Node',
    displayName: 'Node',
    description: 'Contains metrics reported from the Venice Nodes',
    fields: [
      {
        name: 'CPUUsedPercent',
        displayName: 'Percent CPU Used',
        description: 'CPU usage (percent) ',
        units: 'Percent',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'DiskFree',
        displayName: 'Disk Free',
        description: 'Disk Free in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskTotal',
        displayName: 'Total Disk Space',
        description: 'Total Disk Space in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskUsed',
        displayName: 'Disk Used',
        description: 'Disk Used in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskUsedPercent',
        displayName: 'Percent disk Used',
        description: 'Disk usage (percent) ',
        units: 'Percent',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'InterfaceRxBytes',
        displayName: 'Interface Rx',
        description: 'Interface Rx in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'InterfaceTxBytes',
        displayName: 'Interface Tx',
        description: 'Interface Tx in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemFree',
        displayName: 'Memory Free',
        description: 'Memory Free in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemTotal',
        displayName: 'Total Memory Space',
        description: 'Total Memory Space in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemUsed',
        displayName: 'Memory Used',
        description: 'Memory Used in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemUsedPercent',
        displayName: 'Percent Memory Used',
        description: 'Memory usage (percent) ',
        units: 'Percent',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'reporterID',
        displayName: 'Reporting Node',
        description: 'Name of reporting node',
        baseType: 'string',
        jsType: 'string',
      },
    ]
  },
  {
    name: 'SmartNIC',
    objectKind: 'SmartNIC',
    displayName: 'Naples',
    description: 'Contains metrics reported from the Naples',
    fields: [
      {
        name: 'CPUUsedPercent',
        displayName: 'Percent CPU Used',
        description: 'CPU usage (percent) ',
        units: 'Percent',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'DiskFree',
        displayName: 'Disk Free',
        description: 'Disk Free in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskTotal',
        displayName: 'Total Disk Space',
        description: 'Total Disk Space in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskUsed',
        displayName: 'Disk Used',
        description: 'Disk Used in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'DiskUsedPercent',
        displayName: 'Percent Disk Used',
        description: 'Disk usage (percent) ',
        units: 'Percent',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'InterfaceRxBytes',
        displayName: 'Interface Rx',
        description: 'Interface Rx in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'InterfaceTxBytes',
        displayName: 'Interface Tx',
        description: 'Interface Tx in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemFree',
        displayName: 'Memory Free',
        description: 'Memory Free in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemTotal',
        displayName: 'Total Memory Space',
        description: 'Total Memory Space in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemUsed',
        displayName: 'Memory Used',
        description: 'Memory Used in bytes',
        units: "Bytes",
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
      },
      {
        name: 'MemUsedPercent',
        displayName: 'Percent Memory Used',
        units: 'Percent',
        description: 'Memory usage (percent) ',
        baseType: 'number',
        jsType: 'number',
        scaleMin: 0,
        scaleMax: 100,
      },
      {
        name: 'reporterID',
        displayName: 'Reporting SmartNIC',
        description: 'Name of reporting SmartNIC',
        baseType: 'string',
        jsType: 'string',
      },
    ]
  }
];

module.exports = {
  metrics: metrics
}