# $FreeBSD: todo version tag $

KMOD=pnso
SRCS= \
src/osal/linux/kernel/osal_thread.c \
src/osal/linux/kernel/osal_atomic.c \
src/osal/linux/kernel/osal_sys.c \
src/osal/linux/kernel/sim/osal_mem.c \
src/osal/test/osal_test.c \
vnode_if.h

CFLAGS+= -I${SRC_TOP}/sys/ofed/include
CFLAGS+= -I${SRC_TOP}/sys/compat/linuxkpi/common/include
INCDIRS = include src/osal src/osal/test
CFLAGS+= $(INCDIRS:%=-I$(PWD)/%)
CFLAGS+= -D__KERNEL__

.include <bsd.kmod.mk>

CFLAGS+= -Wno-pointer-arith
