/*
 * Copyright (c) 2018, Pensando Systems Inc.
 */

#ifndef PCIEIND_REASON_DEF
#define PCIEIND_REASON_DEF(NAME, VAL)
#endif

#define PCIEIND_REASON_DEF(RSRV0, 0)
#define PCIEIND_REASON_DEF(RSRV1, 1)
#define PCIEIND_REASON_DEF(MSG, 2)
#define PCIEIND_REASON_DEF(UNSUPPORTED, 3)
#define PCIEIND_REASON_DEF(PMV, 4)
#define PCIEIND_REASON_DEF(DBPMV, 5)
#define PCIEIND_REASON_DEF(ATOMIC, 6)
#define PCIEIND_REASON_DEF(PMTMISS, 7)
#define PCIEIND_REASON_DEF(PMRMISS, 8)
#define PCIEIND_REASON_DEF(PRTMISS, 9)
#define PCIEIND_REASON_DEF(DBF2VFIDMISS, 10)
#define PCIEIND_REASON_DEF(PRTOOR, 11)
#define PCIEIND_REASON_DEF(VFIDOOR, 12)
#define PCIEIND_REASON_DEF(BDFOOR, 13)
#define PCIEIND_REASON_DEF(PMRIND, 14)
#define PCIEIND_REASON_DEF(PRTIND, 15)
#define PCIEIND_REASON_DEF(PMRECC, 16)
#define PCIEIND_REASON_DEF(PRTECC, 17)

#undef PCIEIND_REASON_DEF
