#
# Copyright (c) 2018, Pensando Systems Inc.
#

LIBRARY = libpcietlp.a libpcietlp.so
SOURCES = \
	pcietlp.c \
	$(NULL)

LCFLAGS += \
	$(NULL)

TOPDIR = ../../../..
include $(TOPDIR)/make/Makefile.inc
