TOPDIR = ../..
SHAREDLIBRARY = libfsm.so


LCXXFLAGS = \
                        -I../../include \
                        -I../../third-party/spdlog/include

SOURCES = \
        fsm.cc \
        $(NULL)

include $(TOPDIR)/make/Makefile.inc
