---
version: 2.0
targets:
  venice-integ-odd:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make ci-integ-test-odd" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
  venice-integ-even:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make ci-integ-test-even" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
  venice-odd:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make ut-odd" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
  venice-even:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make ut-even" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
  venice-checks:
    commands: [ "sh", "-c", "pwd && ls -l && cd /go/src/github.com/pensando/sw && make ut-build && ./tools/scripts/check-local-files.sh" ]
    owners: ["email:venice-dev@pensando.io"]
    area:
    sub-area:
    feature:
image:
  bind_dir: "/go/src/github.com/pensando/sw"
  work_dir: "/go/src/github.com/pensando/sw"

