package(default_visibility = ["//visibility:public"])
licenses(["notice"])  # MIT license

cc_library(
    name = "libpal_hdrs",
    hdrs = [
        "pal.h",
    ],
    include_prefix = "platform/src/lib/pal/include",
)

